### PR TITLE
[ADD] Adds mass_mailing_template_email module

### PR DESCRIPTION
**Pull request by daramousk**
I am submitting this for an early review

TODO: 
1) tests need to be fixed (I am bumping into https://github.com/odoo/odoo/issues/21530 and I am not sure how to properly hit the endpoint, this is priority No1)
2) Show the templates better on the widget, maybe see how I can generate a jpeg from the template?
3) Everything else that pops up.

cc: @hbrunn

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hi @daramousk , are you going to continue with this PR? The tittle say WIP

**Comment by daramousk** [comment]
@rafaelbn Hello Rafael,

Yes, I have this working on production already so it was not a priority for me, but now that it got some attention I will see it gets done within the next two days.

Thank you.

**Comment by rafaelbn** [comment]
OK thanks. Travis is red :red_circle: yo should take a look please.

`https://travis-ci.org/OCA/social/jobs/580939779#L726`

**Comment by daramousk** [comment]
@rafaelbn Everything should look great now, let me know what you think here.

**Pull request closed without merging**
