### PR TITLE
[IMP] mail_activity_team

### PR DESCRIPTION
**Pull request by etobella**
This PR includes two changes

1 - Adds a default team on activities in order to set it automatically
2 - Improves tests making them more standard

@LoisRForgeFlow @albariera

### CODE REVIEW

**Comment by albariera** [comment]
While doing a functional review we have found a possible bug. If not default user is set in the activity.type, the activity generated can't be marked as done because says that the user is not part of the team.

**Comment by etobella** [comment]
@albariera Now it should be fixed :smile:

**Review by MiquelRForgeFlow — APPROVED** [review]
code LGTM

**Review by AaronHForgeFlow — COMMENTED** [review]
Code LGTM. Where can the types and the default teams by time can be edited? I could not find the way.

Also it would be nice that the default teams could determined by models.

**Comment by etobella** [comment]
You can edit the default team on Activity Team Form (You need to enter with debug)

**Review by AaronHForgeFlow — APPROVED** [review]
Functional + code

**Comment by albariera** [comment]
I am still getting the same problem :crying_cat_face:

**Comment by etobella** [comment]
True, weird.... I added a test in order to avoid getting the regression again. Let's see if now it works :smile:

**Review by albariera — APPROVED** [review]
Thanks! Code and functional review LGTM :+1:

**Comment by MiquelRForgeFlow** [comment]
Please, forward-port it.

**Pull request merged**
