### PR TITLE
[ADD] social_media_icon_extention_tripadvisor

### PR DESCRIPTION
**Pull request by Benniphx**
Tripadvisor Extension for the social media icons from the odoo core

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please follow the same comments as in Xing module. You can also use TripAdvisor logo for the module icon instead of the generic one. Usually, this icon is put at 128x128 px of resolution.

**Comment by Benniphx** [comment]
@pedrobaeza changed all review issues

**Comment by pedrobaeza** [comment]
:+1:

**Comment by hbrunn** [comment]
:+1:

**Pull request merged**
