### PR TITLE
[17.0][MIG] mail_debrand

### PR DESCRIPTION
**Pull request by guestisp**

### CODE REVIEW

**Comment by jcdrubay** [comment]
Hi @guestisp 
You might want to rename your PR with this format: `[17.0][MIG] mail_outbound_static` ;)

**Comment by ahaly-compass** [comment]
Whats the status here?

**Comment by StefanRijnhart** [comment]
Please include https://github.com/OCA/social/pull/1272

**Comment by flotho** [comment]
Hi @guestisp , anychance to retrigger runboat ?

**Comment by StefanRijnhart** [comment]
@flotho it's going to have known issues until https://github.com/OCA/social/pull/1272 is included and its small follow-up https://github.com/OCA/social/pull/1287.

**Comment by nguyenminhchien** [comment]
Hi @guestisp i created https://github.com/guestisp/social/pull/1 to pick https://github.com/OCA/social/pull/1272 and https://github.com/OCA/social/pull/1287
Please review.

**Comment by paddlefish** [comment]
Hi @guestisp I also created a PR onto your PR https://github.com/guestisp/social/pull/2 to pick up what looks like some missed localization work on the 16 branch, fix some code comments and unit test

**Comment by nguyenminhchien** [comment]
Hello, no feedback from the author of this PR. so i create this new one https://github.com/OCA/social/pull/1358

**Comment by novamilky** [comment]
Whats the status here?

**Comment by etobella** [comment]
Probably it is necessary to overseed this PR because the author is not answering

**Comment by StefanRijnhart** [comment]
Closing in favor of https://github.com/OCA/social/pull/1358

**Pull request closed without merging**
