### PR TITLE
[MIG][15.0] mail_optional_follower_notification

### PR DESCRIPTION
**Pull request by robin5210**

### CODE REVIEW

**Comment by robin5210** [comment]
It looks like Jairo Llopis is a historic editor. How should I handle this case?

**Comment by rafaelbn** [comment]
Please @adrienpeiffer @astirpe could you please review this migration to v15?

**Review by adrienpeiffer — APPROVED** [review]
Code review and tests

**Review by rafaelbn — APPROVED** [review]

**Comment by rafaelbn** [comment]
Hello @robin5210 could you please check https://github.com/OCA/social/pull/861#issuecomment-1065975911

Thank you !

**Comment by robin5210** [comment]
The check that failed is not part of this pull request

```
/home/runner/work/social/social/mail_activity_board/static/src/components/chatter_topbar/chatter_topbar.esm.js
  3:1  warning  Imports should be sorted alphabetically  sort-imports

✖ 1 problem (0 errors, 1 warning)
```

Is it appropriate to fix this in this pull request?

**Comment by robin5210** [comment]
@rafaelbn, after further review this just seems a warning. The error itself is a caching issues from pre-commit. Can we first try merging again?

**Pull request merged**
