### PR TITLE
[16.0][MIG] mail_activity_partner: Migration to version 16.0

### PR DESCRIPTION
**Pull request by polqubiq**

### CODE REVIEW

**Comment by hugo-cordoba** [comment]
Hello, check the name of the PR. I think this migration corresponds to the module 'mail_activity_partner' not to the module 'product_pricelist_margin' :)

**Comment by polqubiq** [comment]
> Hello, check the name of the PR. I think this migration corresponds to the module 'mail_activity_partner' not to the module 'product_pricelist_margin' :)

Whoops, you're absolutely right. Well seen! Thank you.

**Review by dariodelzozzo — APPROVED** [review]
Code Review

**Review by valentinagiuliani-rapsodoo — APPROVED** [review]

**Comment by simahawk** [comment]
@polqubiq looks good, tnx. Just one nitpicking step if is possible for you: could you please amend the last commit to be `[16.0][MIG] <module>: Migration to 16.0`? You can see a similar commit for 15.0.

See guidelines https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#how-to

**Comment by polqubiq** [comment]
> @polqubiq looks good, tnx. Just one nitpicking step if is possible for you: could you please amend the last commit to be `[16.0][MIG] <module>: Migration to 16.0`? You can see a similar commit for 15.0.
> 
> See guidelines https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#how-to

@simahawk I think it's not `[16.0][MIG] <module>: Migration to 16.0`. It is `[MIG] $module: Migration to 16.0` instead. I've just made the change. Thanks!

**Comment by simahawk** [comment]
> @simahawk I think it's not `[16.0][MIG] <module>: Migration to 16.0`. It is `[MIG] $module: Migration to 16.0` instead. I've just made the change. Thanks!

image


The odoo version can be there when is a migration :wink: 

/ocabot merge nobump

**Comment by simahawk** [comment]
FTR tests were red because of our servers issue. Should be fixed now.

**Comment by polqubiq** [comment]
> > @simahawk I think it's not `[16.0][MIG] <module>: Migration to 16.0`. It is `[MIG] $module: Migration to 16.0` instead. I've just made the change. Thanks!
> 
> image
> 
> The odoo version can be there when is a migration 😉
> 
> /ocabot merge nobump

I thought that one thing is the name of the pull request and another is the name of the commit :upside_down_face:

**Pull request merged**
