### PR TITLE
[ADD] mail_chatter_thread_colour

### PR DESCRIPTION
**Pull request by etobella**
With this module, users might see easily if a chat comes from a chat or from a record.

We can even define a color for a model :smile: 

Peek 2022-07-27 16-59

### CODE REVIEW

**Review by DavidJForgeFlow — APPROVED** [review]
image
Functional review :+1: code also LGTM!

**Comment by etobella** [comment]
Added the option to change the color of the font too (good in some cases) @LoisRForgeFlow

**Review by LoisRForgeFlow — APPROVED** [review]
Much better now. Functional review LGTM :+1: 

image

**Pull request merged**
