### PR TITLE
[13.0][FWD] email_template_qweb: ease override of values, include defaults

### PR DESCRIPTION
**Pull request by simahawk**
FWD port of https://github.com/OCA/social/commit/cd35bfbec370c0b427b2afee4e6a317838cdb21c from 11.0

### CODE REVIEW

**Review by santostelmo — APPROVED** [review]
With the modifications required in the format_amount and format_datetime import, I tested functionally and seems to work well.

**Comment by simahawk** [comment]
@santostelmo can you fix linting?

**Comment by santostelmo** [comment]
I checked the current report layout with Patrick Gummy and we noticed that the layout is still not correct. I still need to do some customizations. I tag this with WIP.

**Comment by simahawk** [comment]
> I checked the current report layout with Patrick Gummy and we noticed that the layout is still not correct. I still need to do some customizations. I tag this with WIP.

this is not related to this PR but to your internal PR :wink:

**Comment by santostelmo** [comment]
@simahawk now green

**Pull request merged**
