### PR TITLE
[12.0][FIX] mail_activity_board: wrong typo for view extend

### PR DESCRIPTION
**Pull request by ypapouin**
Wrongly used `mail.Chatter.Buttons` instead of `mail.chatter.Buttons`

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
To be merged manually due to https://github.com/OCA/social/issues/851.

**Comment by rafaelbn** [comment]
Please @ypapouin could you please update the version of the module? 

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#version-numbers

**Review by rafaelbn — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
@rafaelbn you can merge it now manually

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
