### PR TITLE
[MIG] mail_optional_follower_notification: Migration to 14.0

### PR DESCRIPTION
**Pull request by ioans73**
Standard migration

### CODE REVIEW

**Comment by JorgeQuinteros** [comment]
LGTM! Functional Review.

**Review by rousseldenis — APPROVED** [review]

**Review by Abranes — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]

**Review by antoniocanovas — APPROVED** [review]
Functional review Ok

**Comment by oreju** [comment]
@ioans73 
Hello, 

Sorry for interruption. Could you provide a fix to solve error that happened during test in Travis CI?

Thank you!

**Comment by alexeirivera87** [comment]
Hello

Is this PR alive?

@ioans73

**Comment by Bilbonet** [comment]
Hello @ioans73 

Module works great! Thanks!
It would be great the same functionality in the sends invoice wizard.

**Comment by etobella** [comment]
/ocabot merge nobump

In case it does not work, as @ioans73 is not responding, we might need to superseed him :thinking:

**Comment by hildickethan** [comment]
superseeded by 
- https://github.com/oca/social/pull/836

**Comment by houssine78** [comment]
@dreispt could you please close this PR as it has been superseed by an already merged PR.

**Pull request closed without merging**
