### PR TITLE
[16.0] [MIG] mail_activity_reply_creator: Migration to 16.0

### PR DESCRIPTION
**Pull request by renda-dev**
Migration of mail_activity_reply_creator to v16

### CODE REVIEW

**Comment by HekkiMelody** [comment]
I think some translation commits got lost while squashing administrative commits

https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Comment by renda-dev** [comment]
> I think some translation commits got lost while squashing administrative commits

Thanks for letting me notice! 
- Re-added translation commits
- `mail_activity_reply_creator` breaks tests for `mail_composer_cc_bcc_account`, so i splitted them.

**Review by HekkiMelody — APPROVED** [review]
Code review, LGTM

**Comment by renda-dev** [comment]
Hello @OCA/social-maintainers,
could anyone take a look at this when they have time? Thanks!

**Review by etobella — APPROVED** [review]
Technical review

**Pull request merged**
