### PR TITLE
Fix mail_inline_css transform hook

### PR DESCRIPTION
**Pull request by simahawk**
The mail module offers a better hook to manipulate html: `render_post_process`.
By using this, we make sure the transform is applied properly
before html tags sanitizing happens,
which can alter - if not screw - the final result.

Finally, it simplifies code :)

Previous commit is a backport from v12 https://github.com/OCA/social/commit/0d68d9dee422befd2e3c1f48d038e1476a3c56ea

### CODE REVIEW

**Comment by simahawk** [comment]
@bealdav @p-tombez would you mind to pass by for a review?

**Review by bealdav — APPROVED** [review]
Thanks a lot

**Comment by simahawk** [comment]
@p-tombez ping :)

**Review by p-tombez — APPROVED** [review]

**Pull request merged**
