### PR TITLE
[FIX] do not use section titles in readme fragments

### PR DESCRIPTION
**Pull request by sbidoul**
This creates inconsistency issues when assembling them in the README.

cc/ @chienandalu

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But why we can use subtitles?

**Comment by sbidoul** [comment]
Because rst infers document structure based on the style used for title underlines. Since we include these fragments in content that have their own structure, there is a risk of conflict. The only exception we made is in HISTORY.rst (one level using tilde `~` underline). Read also [here](https://github.com/OCA/maintainer-tools/blob/master/template/module/readme/USAGE.rst) and [here](https://github.com/OCA/maintainer-tools/blob/master/template/module/readme/HISTORY.rst).

**Comment by pedrobaeza** [comment]
But there can be the need of several sections inside. Can we put in any way this subsections (maybe with `~`)?

Check the original README with 2 sections (now one of them is covered by core, and that's why there's only one subsection, but there can be another case where it's needed): https://github.com/OCA/social/blob/8.0/mass_mailing_custom_unsubscribe/README.rst

**Comment by sbidoul** [comment]
One level with tilde is supported. If we want more we need to document very clearly what characters to use for underlines.

**Comment by pedrobaeza** [comment]
OK, for now, we can merge this one (Travis fail is a glitch).

**Comment by yajo** [comment]
Are there any docs on how to properly use the new readme generator?

**Comment by sbidoul** [comment]
@Yajo the module template is the documentation.

https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst
https://github.com/OCA/maintainer-tools/blob/master/template/module/readme/USAGE.rst
...

**Pull request merged**
