### PR TITLE
[mail_attach_existing_attachment][IMP] Move domain in python in order to allow inheritance

### PR DESCRIPTION
**Pull request by adrienpeiffer**

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
The domain is only evaluated at the beginning, so if you install a module changing the domain you will need to restart the service. Are you aware of that?

I haven't tried this possible workaround in the child module:
```
object_attachment_ids = fields.Many2many(
    domain=lambda self: self._get_object_attachment_domain()
)
```
If it works, it deserves to be put as a comment.

**Comment by hbrunn** [comment]
to my knowledge, those domains are evaluated at view load. Does 10 do something different here?

**Comment by rafaelbn** [comment]
Hi @adrienpeiffer could you please clarify question? Thanks!

**Comment by hbrunn** [comment]
closing due to lack of activity

**Comment by sbidoul** [comment]
@benwillig do you use this PR on your projects? If yes can you followup?

**Comment by benwillig** [comment]
Yes this PR is used in some of my projects and I confirm it's working. @pedrobaeza If you uninstall/install a module which override ```_get_object_attachment_domain```, you won't have to restart the server. This PR should be merge IMHO.

**Review by benwillig — APPROVED** [review]

**Review by sbidoul — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@benwillig please read again my comment. I don't think uninstalling the module will evaluate again the domain.

**Comment by benwillig** [comment]
Yes it does. When using lambda, it's evaluated on the fly, and not when the server starts.

**Comment by pedrobaeza** [comment]
OK, if you are sure about that, I merge.

**Pull request merged**
