### PR TITLE
[12.0][FIX] api multi constrain mistake

### PR DESCRIPTION
**Pull request by jarroyomorales**
Minor fix iterating in `for activity in self:`

@etobella @LoisRForgeFlow @AdriaGForgeFlow

### CODE REVIEW

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Review by etobella — COMMENTED** [review]
LGTM

**Review by etobella — APPROVED** [review]

**Comment by etobella** [comment]
@OCA/social-maintainers This is just a minor patch. Can it be merged?

**Comment by hbrunn** [comment]
one of the reasons why in my code, it's *always* `for this in self:`

**Comment by hbrunn** [comment]
oh now, I forgot ocabot. Sorry, will bump the version number manually

**Pull request merged**
