### PR TITLE
[13.0][IMP] mail_tracking: Port improvements from 12.0

### PR DESCRIPTION
**Pull request by Tardo**
Port: https://github.com/OCA/social/pull/524 and https://github.com/OCA/social/pull/528

cc @tecnativa TT22167

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Check Travis status

**Comment by Tardo** [comment]
Changes done! added https://github.com/OCA/social/pull/528 too

**Comment by pedrobaeza** [comment]
Travis is red

**Review by chienandalu — COMMENTED** [review]
Looks like the new test from 4f9b1c1f181c5ab0d11128d02ef995c67785a695 is missing something

**Comment by Tardo** [comment]
Tests fixed

**Review by rafaelbn — APPROVED** [review]
Thanks :+1:

**Comment by pedrobaeza** [comment]
Let's merge it, although there's other pending PR to be forward-ported

/ocabot merge patch

**Pull request merged**
