### PR TITLE
[12.0][FIX] mass_mailing_custom_unsubscribe: mailing contact contains `opt_out`

### PR DESCRIPTION
**Pull request by yajo**
So we need to explicitly opt-out (:rofl:) that model from the new alternative mechanism for unsubscribing records.

@Tecnativa TT24523

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@sbidoul it seems your switch to PIP has this side effect: https://github.com/OCA/social/pull/555#issuecomment-651687647

**Comment by yajo** [comment]
Now it's failing as it should. Yikes, fixing this is gonna be hard... :facepalm:

**Comment by pedrobaeza** [comment]
Well, I would like to know from @sbidoul why it was originally changed to PIP.

**Comment by pedrobaeza** [comment]
One of the test is due to missing libraries. Maybe it's better to add support for website tours in PIP mode for avoiding that missing libraries.

**Comment by yajo** [comment]
Yes, possibly https://github.com/OCA/maintainer-quality-tools/pull/672 fixes that.

**Comment by pedrobaeza** [comment]
I have reused this PR for fixing the underlying problem after MQT has been applied, so letting the bot to fast-track this for having a green branch when finishes:

/ocabot merge patch

**Pull request merged**
