### PR TITLE
[11.0][FIX] mail_activity_team

### PR DESCRIPTION
**Pull request by AdriaGForgeFlow**
Fix the value of the activity counter. Prevent negative values.

cc ~ @Eficent

### CODE REVIEW

**Comment by AdriaGForgeFlow** [comment]
ping @lreficent @jbeficent @aheficent

**Review by LoisRForgeFlow — APPROVED** [review]
good catch :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Thanks

**Review by HviorForgeFlow — APPROVED** [review]
LGTM :+1:

**Review by jarroyomorales — APPROVED** [review]

**Pull request closed without merging**
