### PR TITLE
12.0 mig mail restrict follower selection

### PR DESCRIPTION
**Pull request by etobella**
This is what we talked in #511

### CODE REVIEW

**Comment by etobella** [comment]
@JoanSForgeFlow

**Comment by JoanSForgeFlow** [comment]
Code and functional review, LGTM :+1:

**Review by JoanSForgeFlow — APPROVED** [review]
Code and functional review, LGTM :+1:

**Review by flotho — APPROVED** [review]
Hi,
Review of code done. LGTM
Thanks for this proposal

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM!

**Pull request merged**
