### PR TITLE
[MIG][14.0]   mail activity creator

### PR DESCRIPTION
**Pull request by JoanMForgeFlow**
Standard Migration to version 14.0

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by etobella — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Review by AaronHForgeFlow — APPROVED** [review]
Functional test :+1:

**Comment by JoanMForgeFlow** [comment]
@dreispt

**Pull request merged**
