### PR TITLE
[MIG] mail_as_letter: Migrated to 10.0

### PR DESCRIPTION
**Pull request by bouvyd**

### CODE REVIEW

**Review by sbidoul — APPROVED** [review]
@dbo-odoo nice to see you around here! 

Tested on runbot. Works fine.

Thanks for the migration.

**Comment by bouvyd** [comment]
@sbidoul 
It's [Hacktoberfest](https://hacktoberfest.digitalocean.com), thought I'd do something useful for the community for the occasion :-)

This one was quite basic to migrate I must say. Nice repo, quite some useful stuff here!

**Comment by sbidoul** [comment]
@dbo-odoo while you are at it can you update the runbot url in the readme? {repo id} is 205.

**Review by pedrobaeza — APPROVED** [review]
Tried on runbot

**Comment by bouvyd** [comment]
@sbidoul Sure, I'll check the readme in the other PRs as well.

**Review by lasley — APPROVED** [review]
👍  code, no test

**Review by rafaelbn — APPROVED** [review]
Tested in runbot

**Pull request merged**
