### PR TITLE
[14.0] [IMP] mail_optional_follower_notification: Add default notify followers in general settings

### PR DESCRIPTION
**Pull request by renda-dev**
Add a settings to set a default for the boolean 'Notifiy Followers' in the wizard

Proposing of https://github.com/OCA/social/pull/1184 for 14.0

If this gets merged I'll fw-port it myself to v16.0

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

@Quan-nhm good for you?

**Review by HekkiMelody — APPROVED** [review]
Code review, LGTM

**Comment by francesco-ooops** [comment]
@pedrobaeza can we have a quick merge or do we need to wait for the bot tag? :)

**Pull request merged**
