### PR TITLE
[FIX] mail_autosubscribe: check partners type

### PR DESCRIPTION
**Pull request by JoelZilli**
make sure partner is a tuple

### CODE REVIEW

**Review by nicomacr — APPROVED** [review]
LGTM

**Comment by JoelZilli** [comment]
We use an if to first see if "partner_id" is a tuple because in this case Odoo tells us that we can only concatenate tuples with tuples. If so, we must cast "follower_ids" as a tuple.
If "partner_ids" does not come as a tuple (i.e. it comes as a list), it is directly concatenated with "follower_ids" which is also a list

**Comment by JoelZilli** [comment]
@yajo could you please review this PR?

**Review by yajo — APPROVED** [review]

**Pull request merged**
