### PR TITLE
[15.0][FIX] mail_tracking: mixed classes

### PR DESCRIPTION
**Pull request by chienandalu**
Addresses issue #947 #1023

In migration #873 the classes DiscussController and MailController which are the result of an upstream functionality split are merge altogether in this module override causing undesired side effects in other modules trying to extend those (i.e.: portal)

cc @Tecnativa TT41432

pinging all involved parts (issuers, migration reviewers) @source-promo @llabusch93 @JasminSForgeFlow @alan196 @nicomacr, @rafaelbn, @gelo-landoo, @manuelregidor

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
I think it's better to split the file in 2, isn't it?

**Comment by chienandalu** [comment]
Ok, done

**Comment by arturoovf** [comment]
Wonder if this issue is fixed?

**Comment by pedrobaeza** [comment]
No while not reviewed and merged. Next time, please perform a review. Merging:

/ocabot merge patch

**Comment by pedrobaeza** [comment]
@chienandalu is this needed in v16?

**Comment by chienandalu** [comment]
> @chienandalu is this needed in v16?

Yes, I already pinged in the migration PR along with some other missing features

**Pull request merged**
