### PR TITLE
[15.0][MIG] mail_drop_target

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

Adapt Odoo's out-of-box dropzone functionality, and remove the dependency of web_drop_target.

@ForgeFlow

### CODE REVIEW

**Comment by etobella** [comment]
Why do you want to remove the dependency on web_drop_target? Code was easier if it was dependent IMO

**Comment by etobella** [comment]
I understand you change, so, don't need to keep the dependancy.
However, it is failing un runbot
image

**Comment by etobella** [comment]
With eml it works fine, but it fails when using msg (taken it from the test files)

**Comment by ygol** [comment]
I think there's a dependency missing (`ReferenceError: base64js is not defined`): 
the library "base64js" that was previously loaded from "web_drop_target".
After adding it to further test:

I tried loading several different msg messages and could get some of them working (plain text email). but most often I get the following error: 
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1347, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1339, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 460, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 433, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/mail_drop_target/models/mail_thread.py", line 90, in message_process_msg
    message_email = self.env["ir.mail_server"].build_email(
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_mail_server.py", line 422, in build_email
    for (fname, fcontent, mime) in attachments:
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: not enough values to unpack (expected 3, got 2)
```


Also got from a different messages:
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1347, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1339, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 460, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 433, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/mail_drop_target/models/mail_thread.py", line 90, in message_process_msg
    message_email = self.env["ir.mail_server"].build_email(
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_mail_server.py", line 395, in build_email
    msg['Message-Id'] = message_id
  File "/usr/lib/python3.8/email/message.py", line 409, in __setitem__
    self._headers.append(self.policy.header_store_parse(name, val))
  File "/usr/lib/python3.8/email/policy.py", line 146, in header_store_parse
    raise ValueError("Header values may not contain linefeed "
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Header values may not contain linefeed or carriage return characters
```
and also
```
Traceback (most recent call last):
  File "/home/odoo/.local/lib/python3.8/site-packages/extract_msg/msg.py", line 55, in __init__
    super().__init__(path)
  File "/usr/lib/python3/dist-packages/olefile/olefile.py", line 1075, in __init__
    self.open(filename, write_mode=write_mode)
  File "/usr/lib/python3/dist-packages/olefile/olefile.py", line 1192, in open
    self._raise_defect(DEFECT_FATAL, "not an OLE2 structured storage file")
  File "/usr/lib/python3/dist-packages/olefile/olefile.py", line 1105, in _raise_defect
    raise exception_type(message)
OSError: not an OLE2 structured storage file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1347, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1339, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 460, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 433, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/user/mail_drop_target/models/mail_thread.py", line 84, in message_process_msg
    message_msg = Message(b64decode(message))
  File "/home/odoo/.local/lib/python3.8/site-packages/extract_msg/message.py", line 26, in __init__
    super().__init__(path, prefix, attachmentClass, filename, delayAttachments, overrideEncoding, attachmentErrorBehavior, recipientSeparator)
  File "/home/odoo/.local/lib/python3.8/site-packages/extract_msg/message_base.py", line 54, in __init__
    super().__init__(path, prefix, attachmentClass, filename, overrideEncoding, attachmentErrorBehavior)
  File "/home/odoo/.local/lib/python3.8/site-packages/extract_msg/msg.py", line 59, in __init__
    raise InvalidFileFormatError(e)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
extract_msg.exceptions.InvalidFileFormatError: not an OLE2 structured storage file
```

**Comment by LoisRForgeFlow** [comment]
Rebased and fixed conflict.

**Comment by nguyenminhchien** [comment]
Hello @JasminSForgeFlow  @LoisRForgeFlow , i just created [this PR ](https://github.com/ForgeFlow/social/pull/5) to import base64js library. Please review.
Thanks,

**Comment by nguyenminhchien** [comment]
@ygol i don't face those errors you had, please share your test files.

**Comment by LoisRForgeFlow** [comment]
> Hello @JasminSForgeFlow @LoisRForgeFlow , i just created [this PR ](https://github.com/ForgeFlow/social/pull/5) to import base64js library. Please review. Thanks,

@nguyenminhchien thanks! your commit has been included here.

However, now a test from a different module is failing. I have tried to reproduce the error in my local with both mail_drop_target and mail_composer_cc_bcc installed, but all ran good in my case. Can you try to reproduce in your side?

**Comment by nguyenminhchien** [comment]
> However, now a test from a different module is failing. I have tried to reproduce the error in my local with both mail_drop_target and mail_composer_cc_bcc installed, but all ran good in my case. Can you try to reproduce in your side?

@LoisRForgeFlow Pull the latest Odoo codebase, the test will be failed. Here is from my local
image

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Works as expected

**Comment by JordiBForgeFlow** [comment]
@JoanSForgeFlow @LoisRForgeFlow Can you review?

**Review by ElmerGForgeFlow — APPROVED** [review]
- The file detection mechanism has been improved, now adeptly managing PDFs and other file formats through the inclusion of the condition **else if (drop_file.name.endsWith(".eml"))**.
- Introducing a reference **(this._fileUploaderRef)** for the file uploader enhances the structure of the code and facilitates more straightforward access to the uploader component.

It works.

**Review by LoisRForgeFlow — APPROVED** [review]
Functional test :+1:

**Pull request merged**
