### PR TITLE
[FIX] 13.0 mail_outbound_static

### PR DESCRIPTION
**Pull request by gurneyalex**
use sudo to get ir.config_parameter, otherwise when normal users try to
send email they get AccessError

### CODE REVIEW

**Comment by gurneyalex** [comment]
This is a forward port of #575

**Comment by gurneyalex** [comment]
I'm happy if this can be fast tracked

**Comment by pedrobaeza** [comment]
I would like to make you happy, but Travis is red :(

**Comment by gurneyalex** [comment]
> I would like to make you happy, but Travis is red :(

I had forgotten to set up pre-commit on my local copy of oca/social... :sweat: 

travis should be fixed shortly

**Pull request merged**
