### PR TITLE
[11.0][IMP] mail_tracking: Discuss - Failed buttons

### PR DESCRIPTION
**Pull request by Tardo**
Improve 'Failed Channel' on Discuss, now can retry or mark as reviewed.

2019-10-21-203521_1920x1080_scrot

cc @tecnativa TT20280

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Not sure what the WIP means

**Comment by Tardo** [comment]
@pedrobaeza I need ensure that this warning is displayed: 
2019-10-21-203842_1920x1080_scrot

**Comment by Tardo** [comment]
Ready to review

**Review by yajo — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
