### PR TITLE
[15.0][ADD] mail_activity_portal: Add in 15.0

### PR DESCRIPTION
**Pull request by ikapasi-initos**

### CODE REVIEW

**Comment by ikapasi-initos** [comment]
@jans23 FYI

**Review by dsolanki-initos — APPROVED** [review]
Code review and Functional test, LGTM!

**Comment by ikapasi-initos** [comment]
Hi, @MiquelRForgeFlow  it would be great if you can add reviews here.

**Comment by manengel** [comment]
@dsolanki-initos @jans23
It seems that this PR is laying around in some....hard to define status. Does this here need some work?

**Comment by jans23** [comment]
@manengel From our perspective it's ready to be reviewed by an OCA reviewer.

**Comment by jans23** [comment]
@pedrobaeza This PR is ready for review from your perspective. Would it be possible to add a "no stale" label to this PR?

**Comment by pedrobaeza** [comment]
@jans23 why don't you review it for unblocking it instead of asking to be there forever?

**Comment by jans23** [comment]
We did one review already (as shown above). If it helps, we can do a second review too. ?

**Comment by pedrobaeza** [comment]
Yes, OCA rules stand for 2 reviews for merging (one of them should be PSC, but in this case, if it's correct, we can continue).

**Comment by alihashaam** [comment]
@pedrobaeza 

We have reviewed this twice internally, so can you tell us how to proceed about this now and secondly, we want to ask that if we need to prepare tests for coverage?

**Comment by pedrobaeza** [comment]
@alihashaam please put then your review here with GitHub procedures (going to "Files changed" tab" and giving the approval).

**Comment by pedrobaeza** [comment]
Coverage tests are always welcome, but they are not mandatory.

**Review by alihashaam — APPROVED** [review]

**Pull request closed without merging**
