### PR TITLE
[16.0][MIG] mail_layout_force

### PR DESCRIPTION
**Pull request by Abranes**
Standard migration to 16.0 from https://github.com/OCA/social/pull/973

### CODE REVIEW

**Comment by Abranes** [comment]
@rafaelbn @OCA/social-maintainers could you reopen please?

**Comment by rafaelbn** [comment]
@Abranes , I cannot reopen see (is disable)

imagen

**Review by dhx — COMMENTED** [review]
@yostashiro AFAICS you did the last migration, do you think this PR looks good?

**Comment by simahawk** [comment]
~Cannot be reopened. You'll have to create a new one :wink:~

**Comment by simahawk** [comment]
Apriti sesamo!

**Comment by simahawk** [comment]
bah, does not work. Please go for a new one :sweat_smile: 

The UI seems buggy as the btn is enabled randomly

image

**Comment by Abranes** [comment]
> bah, does not work. Please go for a new one 😅
> 
> The UI seems buggy as the btn is enabled randomly
> 
> image

Reopened #1333

**Pull request closed without merging**
