### PR TITLE
[14.0][MIG] mail_attach_existing_attachment: Migration to 14.0

### PR DESCRIPTION
**Pull request by ernestotejeda**
Cc @Tecnativa TT30284

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Tested on runbot

**Review by HaraldPanten — CHANGES_REQUESTED** [review]
Not sure if I'm missing something. Testing in runbot:

1- I created a sale order.
2- I attached 2 random files.
3- I tried to log a note and I opened the compose message.
4- I wrote a random text and I selected the two attachments with the corresponding checkbox.
5- I pressed the button to log the note.

Result: The compose message is closed (as usual) but the log note disappears and it's not posted anywhere.

Am I missing something or is one of the repository modules that might be creating this malfunction?

**Comment by pedrobaeza** [comment]
You have to refresh the screen. It's something of Odoo itself.

**Review by HaraldPanten — APPROVED** [review]
Functional review. Tested in runbot

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
