### PR TITLE
[8.0][website_mail_snippet_responsive] New date snippet and some fixes

### PR DESCRIPTION
**Pull request by yajo**
After some R&D we are fixing some bugs found in some mail clients.

Still there's one in Outlook that is now documented in Known Issues.

Also we add a new date snippet that looks like this:
captura el 2016-02-16 a las 17 35 50

@rafaelbn 

(@dgzurita please review the messages for commits I added above yours)

### CODE REVIEW

**Comment by rafaelbn** [comment]
thanks! :+1:

**Comment by antespi** [comment]
Please @Yajo, rebase and resolve conflicts

**Comment by yajo** [comment]
Should be fixed.

**Comment by dgzurita** [comment]
tested in runbot :+1:

**Comment by pedrobaeza** [comment]
Waiting for https://github.com/Yajo/social/pull/11, but :+1:

**Comment by pedrobaeza** [comment]
Please change version number

**Comment by yajo** [comment]
All done.

**Comment by antespi** [comment]
:+1: Cool

**Pull request merged**
