### PR TITLE
[14.0][FIX] mail_debrand: tolerate binary inputs, solve etree FutureWarning

### LINKED ISSUE #684: [14.0] mail_debrand: FutureWarning in log if using python 3.8 and above
Module: mail_debrand
Version: 14.0

WARNING-messages in log during usage of module:

```
2021-03-05 19:02:05,661 329 WARNING demo py.warnings: /mnt/extra-addons/mail_debrand/models/mail_render_mixinANDmail_mail.py:28: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if remove_before and not remove_parent and previous:
 ```

### LINKED ISSUE #702: [14.0] mail_debrand: TypeError: cannot use a string pattern on a bytes-like object
This error occurs in the app email marketing(mass_mailing) by clicking on "Test" in the Mailings tab

 File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1368, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1356, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/addons/mass_mailing/wizard/mailing_mailing_test.py", line 54, in send_mail_test
    mail = self.env['mail.mail'].sudo().create(mail_values)
  File "<decorator-gen-210>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/odoo/addons/mass_mailing/models/mail_mail.py", line 21, in create
    mails = super(MailMail, self).create(values_list)
  File "<decorator-gen-155>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/custom-addons/mail_debrand/models/mail_render_mixinANDmail_mail.py", line 98, in create
    values_list[index]["body_html"] = self.env[
  File "/opt/odoo/custom-addons/mail_debrand/models/mail_render_mixinANDmail_mail.py", line 18, in remove_href_odoo
    has_odoo_link = re.search(r"<a\s(.*)odoo\.com", value, flags=re.IGNORECASE)
  File "/usr/lib/python3.8/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
Exception
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: cannot use a string pattern on a bytes-like object

### PR DESCRIPTION
**Pull request by dreispt**
Closes #684 
Closes #702

### CODE REVIEW

**Comment by CasVissers-360ERP** [comment]
@dreispt 

I still get:
 ```
 File "/home/odoo/src/user/community/mail_debrand/models/mail_render_mixinANDmail_mail.py", line 99, in create
    values_list[index]["body_html"] = self.env[
  File "/home/odoo/src/user/community/mail_debrand/models/mail_render_mixinANDmail_mail.py", line 44, in remove_href_odoo
    parent.getparent().remove(parent)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'NoneType' object has no attribute 'remove'
```

**Comment by dhx** [comment]
might also help with #702

**Comment by dreispt** [comment]
@dhx Can you test this fix and provide feedback please?

**Comment by dhx** [comment]
@dreispt applied the patch and it seems to solve the issue so far

**Comment by dreispt** [comment]
@dhx Can you then approve the PR please? Thanks!

**Review by dhx — APPROVED** [review]
while the res variable doesn't seem to be necessary in the test (in the other functions it's always used in the assertion somehow) - for me the PR seems to work so far

**Comment by dreispt** [comment]
Good point. I fixed that and will proceed with the merge.

**Pull request merged**
