### PR TITLE
[16.0][MIG] mail_activity_creator

### PR DESCRIPTION
**Pull request by bosd**
Standard migration using odoo-module-migrator /ocabot migration mail_activity_creator

### CODE REVIEW

**Comment by bosd** [comment]
Oops, my script test made it into a PR.
Well. lets leave it here :)

**Comment by simahawk** [comment]
@bosd is it a test or what?
We another PR here https://github.com/OCA/social/pull/1169 would be nice to know what to do.... :wink:

**Comment by bosd** [comment]
@simahawk 
I accidentally did the migration of this module. (Was not on my todo list)
The PR states Test, because I was testing the odoo-module-migrator. 

Migration succeeded with this script, so this one can be merged.


The other PR is created after this one.
On first sight not much difference on that PR. Only this has the commit messages according to oca guidelines.

**Comment by bosd** [comment]
Force pushed, to re-trigger gh actions.

**Review by dariodelzozzo — APPROVED** [review]

**Comment by ypapouin** [comment]
I don't understand why this module exists.

Since at least Odoo 12.0, the creator is already visible using the  « i » detail button.
image

If the purpose was just adding the creator in the activity form view, why adding a new `creator_uid` field when `create_uid` already exists ?

This module should be removed from the OCA (too simple according to the rules).

**Pull request closed without merging**
