### PR TITLE
[15.0][MIG] mail_tracking_mass_mailing: Migration to version 15.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT36472

ping @CarlosRoca13 @ernestotejeda 

Supersed of https://github.com/OCA/social/pull/895

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
LGTM :+1:

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Comment by pedrobaeza** [comment]
@LoisRForgeFlow there seems to be a problem with `mail_quoted_reply`:

https://github.com/OCA/social/actions/runs/3913977468/jobs/6690508845#step:8:263

**Comment by chienandalu** [comment]
@sergio-teruel Please add this changes https://github.com/OCA/social/pull/1048/commits/e4bfcc5c29158377c99850b400ce75676a62da6f#diff-109e6922357ddf6655ff54e9e8ec6ee303a1b68e62ce92d54b4f9058c05c7eb0

just the part corresponding to this module. The rest is being ported here https://github.com/OCA/social/pull/1056

**Comment by pedrobaeza** [comment]
Error in tests documented in #1061

**Pull request merged**
