### PR TITLE
[14.0][MIG] mass_mailing_resend: Migration to 14.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 14.0

Please @pedrobaeza and @ernestotejeda can you review it?

@Tecnativa TT30290

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
Have you tried on UI that everything continues the same on this version?

**Comment by victoralmau** [comment]
Yes, I have tested the button in UI and that the state is changed to draft.

**Review by pedrobaeza — APPROVED** [review]
Code review

**Review by CarlosRoca13 — APPROVED** [review]

**Pull request merged**
