### PR TITLE
[15.0][MIG] mail_layout_force

### PR DESCRIPTION
**Pull request by yostashiro**
Standard migration.

@qrtl

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]

**Comment by ivantodorovich** [comment]
Thanks a lot!

/ocabot merge nobump

**Comment by ivantodorovich** [comment]
Weird, I'm not recognized as maintainer

**Comment by yostashiro** [comment]
@ivantodorovich Would it help if I add you as the maintainer in this PR? Thanks for the module btw!

**Comment by ivantodorovich** [comment]
Thank you for migrating it ❤️ 

> Would it help if I add you as the maintainer in this PR? 

The strange thing is that I'm already a maintainer. @OCA-git-bot is ignoring me.
Anyway, let's just wait for someone with merging rights to show up

**Review by Abranes — APPROVED** [review]
LGTM!

**Comment by Abranes** [comment]
@yostashiro can you do a rebase from 15.0?

**Comment by yostashiro** [comment]
> @yostashiro can you do a rebase from 15.0?

@Abranes Done. :D

**Comment by Abranes** [comment]
ping @OCA/social-maintainers

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
