### PR TITLE
[12.0][MIG] Module mail_improved_tracking_value

### PR DESCRIPTION
**Pull request by mbcosta**
Migration mail_improved_tracking_value module, but from version 10 to 12 ( PR migration from 10 to 11 seems freezed ), any problem ? Should it be made first ?

cc @renatonlima @rvalyi

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Could you use the commit history of https://github.com/OCA/social/pull/678 instead, please? Using [method](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0), but replacing the `origin/12.0..origin/11.0` by `origin/12.0..ForgeFlow/11.0-mig-mail_improve_tracking_value` (previous adding our remote and fetching the branch).

**Comment by mbcosta** [comment]
Hi @MiquelRForgeFlow thanks for quick answer, the commit history now is based in your migration PR.

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]
@mbcosta What could be happening in the runbot?

**Review by mileo — APPROVED** [review]

**Pull request merged**
