### PR TITLE
[15.0][MIG] mail_activity_team

### PR DESCRIPTION
**Pull request by BernatPForgeFlow**
Standard migration to 15.0

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Apart of the issue commented, the rest seems to work good :+1:

**Review by olgamarcocb — APPROVED** [review]
LGTM :+1:

**Review by AaronHForgeFlow — COMMENTED** [review]
I just realized that issue is also affecting previous versions of the module. Perhaps we can just put that in the roadmap as a future improvement and move forward with this PR.

**Comment by JoanMForgeFlow** [comment]
@etobella Could you try to merge again this module?
Thanks!

**Comment by etobella** [comment]
Can you rebase it? Something is failing...

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Comment by BernatPForgeFlow** [comment]
@etobella Ready to merge. Thanks.

**Comment by BernatPForgeFlow** [comment]
Now it works as desired. Reviews are welcome!

cc @ForgeFlow 
@ChrisOForgeFlow 
@etobella

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review :+1:  Issues solved

**Review by etobella — APPROVED** [review]
LGTM

**Pull request merged**
