### PR TITLE
[IMP] Apply copier template

### PR DESCRIPTION
**Pull request by yajo**
This is general repo maintenance.

@Tecnativa

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]

**Review by Tardo — APPROVED** [review]

**Comment by hbrunn** [comment]
thanks @Yajo, could you apply pre-commit here too? Then the v13 branch is completely up to date

**Comment by yajo** [comment]
I just published https://github.com/OCA/oca-addons-repo-template/releases/tag/v1.1.3 which includes https://github.com/OCA/oca-addons-repo-template/pull/51 which fixes https://github.com/pre-commit/mirrors-prettier/issues/6 which allowed me to `pre-commit run -a` which should make bots happy, so this should be ready.

**Comment by Tardo** [comment]
Looks good, thanks @Yajo

**Pull request merged**
