### PR TITLE
[MIG] mail_restrict_follower_selection: Migration to 14.0

### PR DESCRIPTION
**Pull request by olgamarcocb**
Standard Migration to 14.0

### CODE REVIEW

**Review by etobella — APPROVED** [review]

**Comment by michaelslade54** [comment]
I have tested this migration and it appears to be missing this fix #581 , which is also missing in v13. There is an open pull request  #648 for v13 which includes extra tests, however it has not been merged yet.

This fix will ensure that the res_model is always in the context. I am not sure the best course of action to ensure this fix is captured in v14.

**Comment by rafaelbn** [comment]
Please @etobella @olgamarcocb can you answer this comment https://github.com/OCA/social/pull/823#issuecomment-1034543862

Lets review, answer and get this merged

Thanks 😄

**Review by albariera — APPROVED** [review]
LGTM 👍

**Pull request merged**
