### PR TITLE
[15.0][MIG] mail_tracking

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Comment by nicomacr** [comment]
@JasminSForgeFlow check the pre-commit errors, please

**Comment by JasminSForgeFlow** [comment]
> @JasminSForgeFlow check the pre-commit errors, please

Hi @nicomacr,

pre-commit error is because I use OWL JS, I think have to update pre-commit for its check.

**Comment by pedrobaeza** [comment]
Check the part in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0 about `esm` name.

**Comment by JasminSForgeFlow** [comment]
Hi @nicomacr,

pre-commit fixed now.

Thanks @pedrobaeza

**Review by alan196 — APPROVED** [review]
Functional Test 👍 

Tested in production environment

**Review by nicomacr — APPROVED** [review]
LGTM

**Comment by HaraldPanten** [comment]
@rafaelbn @MiquelRForgeFlow @AaronHForgeFlow 

Is this PR ready to merge?

THX!

**Review by manuelregidor — APPROVED** [review]
LGTM

**Review by ghost — APPROVED** [review]
Functional test OK.

**Comment by ghost** [comment]
@yajo @etobella @pedrobaeza Can it be merged? Thanks

**Review by rafaelbn — APPROVED** [review]

**Comment by HaraldPanten** [comment]
> @rafaelbn The merge process could not be finalized, because command `git push origin 15.0-ocabot-merge-pr-873-by-rafaelbn-bump-patch:15.0` failed with output:
> 
> ```
> To https://github.com/OCA/social
>  ! [rejected]          15.0-ocabot-merge-pr-873-by-rafaelbn-bump-patch -> 15.0 (fetch first)
> error: failed to push some refs to 'https://***@github.com/OCA/social'
> hint: Updates were rejected because the remote contains work that you do
> hint: not have locally. This is usually caused by another repository pushing
> hint: to the same ref. You may want to first integrate the remote changes
> hint: (e.g., 'git pull ...') before pushing again.
> hint: See the 'Note about fast-forwards' in 'git push --help' for details.
> ```

Strange reaction. I see that the PR has been merged 🤔

**Pull request merged**
