### PR TITLE
[8.0][ADD] mail_opt_out_default addon

### PR DESCRIPTION
**Pull request by astirpe**
This module sets the default value of the field "Opt-Out" to True while creating a Partner.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This can be easily done with default values through standard Odoo, so I see no value added in this module, sorry.

:-1:

**Comment by lasley** [comment]
I second the 👎  - if you need a tutorial on defaults - https://blog.laslabs.com/2015/09/odoo-setting-defaults-fields/

**Comment by astirpe** [comment]
@pedrobaeza @lasley this module is evolved in the meanwhile:
https://github.com/onesteinbv/addons-onestein/tree/10.0/mail_opt_out_default
maybe you could take a look at it and let me know in case it could be of interest for OCA.
In particular, the configuration feature was reviewed and made per Company.
Thank you!

**Comment by pedrobaeza** [comment]
Well, I'm still think similar to my previous comment on this one. Thanks for telling us.

**Pull request closed without merging**
