### PR TITLE
[MIG] microsoft_outlook_single_tenant: Migration to 15.0

### PR DESCRIPTION
**Pull request by santostelmo**
Migrating `microsoft_outlook_single_tenant` from 14.0 -> 15.0

### CODE REVIEW

**Review by ajaniszewska-dev — APPROVED** [review]

**Review by leemannd — APPROVED** [review]

**Comment by ajaniszewska-dev** [comment]
@pedrobaeza  could we merge this one?

**Comment by pedrobaeza** [comment]
The commits contents are incorrect, as there shouldn't be the version change in the black/isort commit. Please follow migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

**Comment by santostelmo** [comment]
> version change in the black/isort commit

I am not sure about what you mean about version change in the black/isort commit ?

**Comment by santostelmo** [comment]
@pedrobaeza I changed the commit. Hope I interpreted well what you mean

**Comment by pedrobaeza** [comment]
Yes, now the commits are correctly distributed, but there's a general error in the repository. @LoisRForgeFlow please fix mail_quoted_reply module tests.

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza The fix was already proposed by Stefan https://github.com/OCA/social/pull/1039 :)

**Pull request merged**
