### PR TITLE
[12.0][FIX] mass_mailing_list_dynamic: Avoid error on shared contacts

### PR DESCRIPTION
**Pull request by pedrobaeza**
- Create a contact with tag "X"
- Create a dynamic mailing list fully sync with criteria for tag "X".
- Sync it.
- Create a second mailing list non dynamic.
- Try to add the contact to second mailing list.

You get an error in this case, and it shouldn't happen.

TT25002

### CODE REVIEW

**Review by ernestotejeda — COMMENTED** [review]
Code review :+1:

**Review by ernestotejeda — APPROVED** [review]
Functional review :+1:

**Review by rafaelbn — APPROVED** [review]
:+1:

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
