### PR TITLE
[MIG] mail_debrand: Migration to v14

### PR DESCRIPTION
**Pull request by SodexisTeam**
@stephankeller

### CODE REVIEW

**Comment by cbssolutions** [comment]
not working at all. all wrong

**Comment by atchuthan** [comment]
@alexteodor 
Sorry, I pushed the wrong branch.
Currently, debrand works for the English language only.  We will investigate why the change does not work for other languages.

**Comment by cbssolutions** [comment]
see another push request from alexteodor that is working for all the
languages ... templates

**Comment by SodexisTeam** [comment]
closing this PR in favour of https://github.com/OCA/social/pull/655

**Pull request closed without merging**
