### PR TITLE
[IMP] mail_activity_team: include meetings

### PR DESCRIPTION
**Pull request by etobella**
This PR allows to use teams on meetings (inherited from mail_activity_board). Now, a new privacy option is added to calendar.events, as you are able to read all the meetings of your team

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
cc @ageficent @aheficent

**Comment by etobella** [comment]
@jarroyomorales

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests passed :+1: 

BTW it would be awesome if we include an options to see Team's events in the calendar, above "Everybody's calendars":
image

Nice to have in the future

**Review by AdriaGForgeFlow — APPROVED** [review]

**Comment by etobella** [comment]
> Functional tests passed +1
> 
> BTW it would be awesome if we include an options to see Team's events in the calendar, above "Everybody's calendars":
> image
> 
> Nice to have in the future

Intersting, I will  check. I also found a security issue, so we need to wait for it first :smile:

**Comment by AaronHForgeFlow** [comment]
> Intersting, I will check. I also found a security issue, so we need to wait for it first

:smile: It seems to me that is gonna be hard, so it's ok to leave it for next version

**Comment by etobella** [comment]
Not as hard as you think :wink:

**Comment by etobella** [comment]
Now it works, but I don't like the behavior. Also, it is hard to attach some kind of patch because there is no possible hooks. I will remove it, and add this option on the search bar

**Comment by LoisRForgeFlow** [comment]
There is a little conflict because of a recent fix merge, can you check?

**Comment by etobella** [comment]
@lreficent conflict avoided :wink:

**Review by jarroyomorales — APPROVED** [review]
LGTM! :+1:

**Pull request closed without merging**
