### PR TITLE
[10.0] mail_show_follower

### PR DESCRIPTION
**Pull request by eLBati**
From https://github.com/OCA/social/pull/711

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
👍

**Review by Shide — APPROVED** [review]
LGTM

**Comment by rafaelbn** [comment]
Hello @eLBati , This branch has no conflicts with the base branch could you fix it please?

**Comment by eLBati** [comment]
Hi @rafaelbn are you referring to CI?

**Comment by rafaelbn** [comment]
> Hi @rafaelbn are you referring to CI?

Yes @eLBati . How would you proceed?

**Comment by rafaelbn** [comment]
Hello @eLBati in order to merge this one fixing travis is needed, could you fix it?

**Pull request closed without merging**
