### PR TITLE
[14.0][ADD] mail_filter_adressee_by_contact

### PR DESCRIPTION
**Pull request by Kev-Roche**
New module to filter adressees on mails by partners, partner contacts and users. 
To avoid unnecessary dependencies, we haven't included tests, not sure if it is mandatory in this case.

### CODE REVIEW

**Comment by sebastienbeau** [comment]
please remove the "s" of contact. By convention we never create module with plurial

**Comment by rafaelbn** [comment]
Hello @sebastienbeau @Kev-Roche @legalsylvain would you like to make a Fridays review to this one? 😄

**Review by sebastienbeau — APPROVED** [review]
Lgtm code review and use it in production

**Comment by HaraldPanten** [comment]
Is the name of the module correct?

**Comment by rafaelbn** [comment]
Hello @Kev-Roche , please answer this https://github.com/OCA/social/pull/822#issuecomment-1065243668 a gogogo to the merge! 😄 Thank!

**Comment by Kev-Roche** [comment]
> Is the name of the module correct?
@HaraldPanten, @rafaelbn 
Yes it is

**Review by rafaelbn — APPROVED** [review]
LGTM 👍

**Pull request merged**
