### PR TITLE
[15.0][MIG] mail_layout_preview: Migrate to version 15.0

### PR DESCRIPTION
**Pull request by sonhd91**
Supersedes https://github.com/OCA/social/pull/1085
To handle cases where templates without records may raise errors during preview rendering, add condition check in the `_compute_layout_preview_url` function.

### CODE REVIEW

**Comment by sonhd91** [comment]
Hello @simahawk, can you take a look ?

**Comment by simahawk** [comment]
@sonhd91 LG. Can you please cleanup the commits? The last commit seems to not contain just the fix. It would be also nice if it says

```
[fix] mail_layout_preview: no record to render

$short_explanation
```

**Comment by sonhd91** [comment]
> @sonhd91 LG. Can you please cleanup the commits? The last commit seems to not contain just the fix. It would be also nice if it says
> 
> ```
> [fix] mail_layout_preview: no record to render
> 
> $short_explanation
> ```

Updated

**Review by simahawk — APPROVED** [review]
Thanks! Is the fix to be backported?

**Comment by sonhd91** [comment]
> Thanks! Is the fix to be backported?

I just did it

**Pull request merged**
