### PR TITLE
[15.0][MIG] mail_activity_partner

### PR DESCRIPTION
**Pull request by JoanMForgeFlow**
Standard migration to version 15.
@MariaDforgeflow
@dreispt
@AaronHForgeFlow 
@bernatpforgeflow

### CODE REVIEW

**Review by mariadforgeflow — APPROVED** [review]
LGTM

**Review by BernatPForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review, works fine

**Pull request merged**
