### PR TITLE
[MIG] mail_tracking_mass_mailing: Migration to 15.0

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by nicomacr** [comment]
Pending merge this [PR](https://github.com/OCA/social/pull/873)

**Comment by grindtildeath** [comment]
@nicomacr Can you please check if https://github.com/OCA/social/pull/908 is needed?

**Review by alan196 — APPROVED** [review]
Technical Review 👍

**Comment by sergio-teruel** [comment]
@nicomacr Can you fix the tests?

**Comment by pedrobaeza** [comment]
Superseded by #1022

**Pull request closed without merging**
