### PR TITLE
[15.0][MIG] mail_quoted_reply

### PR DESCRIPTION
**Pull request by jonasbuchholz**
Migration of mail_quoted_reply to 15.0. The differences between 14.0 and 15.0 required some changes to the module structure. Most notably, the quote isn't using a template anymore, but instead a formatted string is passed to the mail composer in the context.

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Hi @jonasbuchholz Module has been in v14 for a while (https://github.com/OCA/social/tree/14.0/mail_quoted_reply) and it seems you lost a bit of the commit history, could you fix it?

Thanks!

**Comment by jonasbuchholz** [comment]
Hi @LoisRForgeFlow, I completely missed that, thanks! I added the missing commits.

**Comment by rodolphe-kincy** [comment]
Hi, for what it's worth the module is working on my v15 dev database. How may I help to push an official v15 version of this module ?

**Comment by jonasbuchholz** [comment]
It appears that some checks have been failing because of out-dated pre-commit hooks. A rebase resolved that issue. I also signed the OCA CLA in the meantime.

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
@jonasbuchholz Thanks for correcting the commit history.

I have done a functional review and it looks good, there is only a small detail that I think should be improved. When the composer wizard is open with the reply quoted, I miss a initial blank line to start to type your reply, otherwise you need to click enter, and the remove the new quote that is open:

image

**Comment by jonasbuchholz** [comment]
@LoisRForgeFlow Thanks for your suggestion, that makes a lot of sense. I added blank lines before the block quote to make typing a reply more user friendly.

**Review by LoisRForgeFlow — APPROVED** [review]
It looks great now! :+1:

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
