### PR TITLE
[17.0][FIX] mail_activity_board: hide button if has no activities

### PR DESCRIPTION
**Pull request by astirpe**
Fixes https://github.com/OCA/social/issues/1467

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
Functional review. I think this should be merged with priority. The bug is all over.

**Comment by CasVissers-360ERP** [comment]
Video with the bug: https://app.screencastify.com/v3/watch/r21Jfcvl79jQZx1ulKjH

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Pull request merged**
