### PR TITLE
[WIP] 14.0 mig fetchmail thread default

### PR DESCRIPTION
**Pull request by gfcapalbo**
Migrated fetchmail_thread_default
Preserved commit history and did the checks specified in 
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

verified model fields and  view names, no changes seem to be required.

### CODE REVIEW

**Comment by thomaspaulb** [comment]
We need to include [this fix](https://github.com/OCA/social/pull/656) also, because from Odoo 13.0 and up the context key value has changed to `default_fetchmail_server_id`.

**Comment by gfcapalbo** [comment]
> 

Thanks tom . I cherry picked the commit in here as well.  I hadn't checked name changes in context keys .

**Comment by thomaspaulb** [comment]
@gfcapalbo Could you fix pre-commit and tests

**Comment by gfcapalbo** [comment]
@thomaspaulb fixed

**Comment by thomaspaulb** [comment]
@gfcapalbo Hmm.

- Undo the last commit
- Fix the linting thing with your name as a separate fixup of the original commit
- Fix the test with a separate fixup of the other guy's commit
- `git rebase -i --autosquash` will now put 2 and 2 together
- force push

We'll now be left with two commits, and the second one will be easy to cherry-pick-backport back to 13.0

**Review by thomaspaulb — CHANGES_REQUESTED** [review]
Minor git nitpick before approval

**Comment by gfcapalbo** [comment]
@thomaspaulb rebasing done. CI still passing.

**Review by thomaspaulb — APPROVED** [review]

**Review by thomaspaulb — APPROVED** [review]

**Comment by thomaspaulb** [comment]
@NL66278 Maybe a second review?

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Pull request merged**
