### PR TITLE
[MIG] mail_tracking_mass_mailing: Migration to 13.0

### PR DESCRIPTION
**Pull request by zaoral**

### CODE REVIEW

**Comment by zaoral** [comment]
cc @jjscarafia

**Comment by zaoral** [comment]
@pedrobaeza @ernestotejeda @chienandalu @cubells @antespi

Hi to everyone!
Here is the migration of mail_tracking_mass_mailing module to 13.0.
Please review and let me know any suggestion

Best Regards

cc @jjscarafia

**Review by chienandalu — COMMENTED** [review]
Thanks @zaoral !

Looks good, although the pre-commit commit should come before the migration one. That way you could amend easily the changes if requested.

**Comment by pedrobaeza** [comment]
Yes, please follow the procedure put in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

**Comment by zaoral** [comment]
Hi @chienandalu @pedrobaeza 

I have updated the PR with your suggestions and following procedure in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0. Please review went you can and let me know any other thing missing.

Best Regards

**Review by chienandalu — APPROVED** [review]
Thanks! :+1:

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
