### PR TITLE
[14.0] mail_send_copy: description wording

### PR DESCRIPTION
**Pull request by petrus-v**

### CODE REVIEW

**Comment by petrus-v** [comment]
This is an intent to fix #709, at least clarify the module promise!

@legalsylvain as discussed here is a suggestion !

As told, in the mean time I've figured out that the default Odoo behavior makes no sense to send mail from an other user (the sale user) than the current user (the account user) so I've changed email template to avoid:

* sender receiving email twice
* user do not receive any copy

regards,

**Review by legalsylvain — APPROVED** [review]
Makes sense.

thanks for improving the description.

**Comment by legalsylvain** [comment]
CC :@quentinDupont

**Review by quentinDupont — APPROVED** [review]

**Pull request merged**
