### PR TITLE
[14.0][MIG] mail_optional_autofollow: Migration to 14.0

### PR DESCRIPTION
**Pull request by baimont**
https://github.com/OCA/social/issues/620

Migration of mail_optional_autofollow to 14.0

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by rafaelbn — APPROVED** [review]
LGTM 👍 OM

**Review by houssine78 — APPROVED** [review]

**Comment by houssine78** [comment]
Hi @rafaelbn this one ready for merging :)

**Comment by houssine78** [comment]
@rafaelbn any chance to get this merged during these oca days ? 

thank you !

**Pull request merged**
