### PR TITLE
[FIX] mail_activity_reply_creator: check if action is not False

### PR DESCRIPTION
**Pull request by ilyasProgrammer**

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional OK!

Solves the following error: https://recordit.co/Cq4XDovVpM

**Review by Aldeigja — APPROVED** [review]
LGTM

**Comment by francesco-ooops** [comment]
@simahawk quick fix merge? :)

**Comment by simahawk** [comment]
@ilyasProgrammer if you set yourself as a maintainer of the module you'll be able to merge such PRs upon approval ;)

/ocabot merge patch

**Pull request merged**
