### PR TITLE
[MIG] mail_notification_custom_subject: Migration to 14.0

### PR DESCRIPTION
**Pull request by naglis**
Most notable changes:
- `mail.thread` `message_post` and `mail.template` `_render_template` signatures changed;
- Changed `mail.message.custom.subject` `model_id` `ondelete` attribute to
  `cascade` (the default for required fields is `restrict`) as you now cannot have `ondelete="restrict"` for IR models: https://github.com/odoo/odoo/blob/f964b761eae32016e36dd9d39cc2c35fc2270eba/odoo/fields.py#L2601-L2606:
    > `Field model_id of model mail.message.custom.subject is defined as ondelete='restrict' while having ir.model as comodel, the 'restrict' mode is not supported for this type of field as comodel.`
- (_Tests_) `assertEqual` instead of `assertEquals` (deprecated);
- (_Tests_) `SavepointCase` + `tracking_disable=True` context to reduce the number of queries.

### CODE REVIEW

**Review by hbrunn — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
Can you please squash the administrative commits into the migration one?

Selección_019

**Comment by naglis** [comment]
> Can you please squash the administrative commits into the migration one?

@pedrobaeza, it is done.

**Pull request merged**
