### PR TITLE
[12.0][MIG] mail_template_multi_report: Migration to 12.0

### PR DESCRIPTION
**Pull request by ioans73**
Standard migration to 12.0

### CODE REVIEW

**Comment by pedrocs-exo** [comment]
Hi,

What's the status on this PR? Is it abandoned? Do you need a review or help?

**Comment by ioans73** [comment]
Hi @pedrocasi,
It is pending review.

**Review by pedrocs-exo — APPROVED** [review]

**Review by tarteo — APPROVED** [review]
Tested locally works perfectly. Only remark is that `report_template_id` should be required.

image

**Review by angelmoya — APPROVED** [review]

**Comment by angelmoya** [comment]
Hi @ioans73, FYI I plan to migrate to v 14.0

**Comment by sbejaoui** [comment]
Hi @ioans73 ,

thanks for this PR, can you check travis so it can be merged.

**Comment by ioans73** [comment]
@sbejaoui done! 🍏

**Review by sbejaoui — APPROVED** [review]

**Comment by sbejaoui** [comment]
@dreispt this PR is ready to merge

**Comment by ioans73** [comment]
@pedrobaeza Could you reopen this PR please?

**Pull request closed without merging**
