### PR TITLE
[14.0][MIG] - mail_optional_follower_notification

### PR DESCRIPTION
**Pull request by sbejaoui**

### CODE REVIEW

**Review by dreispt — DISMISSED** [review]

**Comment by dreispt** [comment]
Can you check https://github.com/OCA/social/pull/708 ?

**Comment by rousseldenis** [comment]
@sbejaoui Could you review the one pointed by @dreispt as it was created before ?

@dreispt @ioans73 Maybe we can include imrovements done here (SavepointCase in tests)?

**Comment by ioans73** [comment]
@rousseldenis applied improvements

**Comment by hildickethan** [comment]
superseeded by 
- https://github.com/oca/social/pull/836

**Comment by houssine78** [comment]
@dreispt could you please close this PR as it has been superseed by an already merged PR.

**Pull request closed without merging**
