### PR TITLE
[UPD] Python to 3.6 to support latest pylint

### PR DESCRIPTION
**Pull request by thomaspaulb**
Try to fix Travis builds for 12.0 OCA/social

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@OCA/social-maintainers  @moylop260 

https://github.com/OCA/social/pull/960 and https://github.com/OCA/social/pull/658 are failing because of:

```
$ travis_install_nightly
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
ERROR: Could not find a version that satisfies the requirement pylint-plugin-utils==0.7 (from -r /home/travis/maintainer-quality-tools/travis/pylint_odoo_requirements.txt (line 1)) (from versions: 0.1, 0.1.1, 0.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.6, 0.3, 0.4, 0.5, 0.6)
ERROR: No matching distribution found for pylint-plugin-utils==0.7 (from -r /home/travis/maintainer-quality-tools/travis/pylint_odoo_requirements.txt (line 1))
```

It's because [pylint-plugin-utils 0.7](https://pypi.org/project/pylint-plugin-utils/#history) does not support Python 3.5 anymore.

I don't know how important it is to keep testing v12.0 modules with Python 3.5 - I can solve like this by bumping Python to 3.6, or try to:

1. pin `maintainer-quality-tools` to a commit that used a lower version of Pylint
2. add an environment variable to `maintainer-quality-tools` [somewhere here](https://github.com/OCA/maintainer-quality-tools/blob/master/travis/travis_install_nightly#L10) with which you can pin the `pylint` or `pylint-plugin-utils` version to something other than `master`
3. Propose a change to [this file](https://github.com/OCA/pylint-odoo/blob/main/requirements.txt) that picks 0.6 for Python <= 3.5, and an accompanying Pylint version that works

**Comment by pedrobaeza** [comment]
Switch to GitHub actions with the copier template.

**Comment by thomaspaulb** [comment]
@pedrobaeza Do you mean "switch the repo to runboat fully", or is this something new?

**Comment by pedrobaeza** [comment]
I mean switch the repo to use GitHub actions instead of Travis, and that's got running copier against the template we have in https://github.com/OCA/oca-addons-repo-template/ and selecting such option:

```
pipx run copier copy https://github.com/OCA/oca-addons-repo-template/ .
```

**Comment by thomaspaulb** [comment]
Ah yes, like @sbidoul mailed about. Giving it a shot here:

https://github.com/OCA/social/pull/996

**Pull request closed without merging**
