### PR TITLE
[15.0][MIG]mass_mailing_list_dynamic: Migration to 15.0

### PR DESCRIPTION
**Pull request by XanderDeJaegere**
Used pull request #825 for mass_mailing_partner dependency

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please rebase now that the dependency is merged to see if all is correct?

**Comment by gregory-moka** [comment]
> Can you please rebase now that the dependency is merged to see if all is correct?

@XanderDeJaegere 😃

**Comment by rafaelbn** [comment]
/ocabot rebase

@XanderDeJaegere

**Comment by rafaelbn** [comment]
Great, ready to review! 👍 

@moduon MT-2479

**Review by fcvalgar — APPROVED** [review]
LGTM Thank you

**Review by nguyenminhchien — APPROVED** [review]
lgtm

**Pull request merged**
