### PR TITLE
[PORT][9.0] mail_activity 

### PR DESCRIPTION
**Pull request by andreparames**
This a port to v9 of the port done in PR #204. 

I've had to drop the `mixin` approach, since the Odoo v9 models mechanism doesn't work well with them (in particular, the new-style computed fields of the models that got the mixin injected into them stopped working well).

Instead, I created a decorator that directly updates the class as it is being loaded by Python, which means that as far as the Odoo mechanism is concerned, we just used a regular inheritance and added the fields manually.

### CODE REVIEW

**Comment by hbrunn** [comment]
you might be interested in the new commits I just pushed there (no review from my side, would be a bit pointless...)

**Comment by andreparames** [comment]
@hbrunn thanks for the heads-up. I thought the plan was to keep the UI in a separate module?

**Comment by hbrunn** [comment]
it still is, but for the time being, I keep it together because it simplifies development. When mergeability come close, I'd reasses if it's a good idea or not with the splitting

**Comment by JordiBForgeFlow** [comment]
Superseded by https://github.com/OCA/social/pull/286

**Pull request closed without merging**
