### PR TITLE
[10.0][MIG] mass_mailing_unique

### PR DESCRIPTION
**Pull request by pedrobaeza**
Standard migration

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Relevant commit is 92ff260

**Comment by pedrobaeza** [comment]
@chienandalu @cubells please review

**Review by yajo — APPROVED** [review]
Code & functional review

**Review by chienandalu — APPROVED** [review]
:+1:

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test.

**Pull request merged**
