### PR TITLE
[14.0][MIG] mail_outbound_static: Migration to 14.0

### PR DESCRIPTION
**Pull request by pierre-pizzetta**
Standard Procedure

### CODE REVIEW

**Comment by kiwinesian** [comment]
Hi @pierre-pizzetta 

I'm just wondering if this particular branch of yours should fix the mail_outbound_static in v14?
I just tried to install it and it hasn't taken the "Mail From" field - still from the user account.

I did accidentally installed the old v13 prior installing this though.

Just wondering if it is still a work in progress.

Thank you so much!!

**Comment by pierre-pizzetta** [comment]
We're currently using it in production on 14.0 and it's behaving properly, the mail are being sent from the 'smtp_from' address added on the outbound server by the module, the user's email is being used in the 'reply to' field. Behavior didn't change from the 13.0 version, so even if you installed 13.0 version first it should have worked right away too.

**Comment by kiwinesian** [comment]
Thanks for your prompt reply!

Hmmm.. interesting.. doesn't quite work in my environment - docker based.

I tested it on 2 different environments and they are not picking up the
'Email From' field - still picking up the user's email address.

Also restarted the docker but doesn't work yet.

But yes, I did have v13 and it was working fine in v13.

I'll play around a little bit more..

Thank you for your help!

**Comment by pierre-pizzetta** [comment]
Feel free to give me any update on how I could replicate your specific issue, or test quickly on most recent runbot instance with a test mail account if you have on http://runbot.odoo-community.org/runbot/build/3454374

**Comment by kiwinesian** [comment]
Thanks Pierre!

I think it was an administrator error. ;P
I was testing it using my personal account in the 'Outgoing Email Server'
where the error happened; the 'Test connection'

I ended up creating a new account with the exact email address. Tested from
the same place and it worked!

Then I went back to personal account and try to trigger an email using
'Send Message' only to find out that it worked too; probably has been
working.

Not sure if this is the expected behaviour though.

Thank you so much for your help! :)

**Review by atchuthan — APPROVED** [review]

**Review by SimoneVagile — APPROVED** [review]

**Review by CasVissers-360ERP — APPROVED** [review]
Functional test

**Comment by atchuthan** [comment]
@kiwinesian please check your reviews and let us know your feedback such that we can ask the OCA maintainer to merge this PR.

**Comment by kiwinesian** [comment]
Hi there,

I downloaded the module from the v.14 branch. Looks good so far!

Thank you for maintaining it!..🙏

**Comment by gurneyalex** [comment]
apparently this module is not needed in 14.0 : https://github.com/odoo/odoo/pull/70854

**Comment by kiwinesian** [comment]
I think its still needed considering for some SMTP that requires the same
sender address.

Odoo overwrites this individual email by default

**Pull request merged**
