### PR TITLE
[18.0][MIG] mail_restrict_follower_selection: Migration to 18.0

### PR DESCRIPTION
**Pull request by Kimkhoi3010**

### CODE REVIEW

**Comment by TDu** [comment]
@Kimkhoi3010  Have you tried this in the UI, because on runboat it seems to me that I can not select any follower on contact although the domain for it is `[(1, '=', 1)]`
I may be testing it wrong !?
test-mail-restrict-follower-

**Comment by Kimkhoi3010** [comment]
Hi @TDu, 
I have tested on UI and there is no error as you mentioned, I tried with domain as [( 1, '=', 1)] as you mentioned
Screencast from 29-10-2024 11_58_35

**Comment by Kimkhoi3010** [comment]
Hi @TDu, 
I have tested on UI and there is no error as you mentioned, I tried with domain as [( 1, '=', 1)] as you mentioned
Screencast from 29-10-2024 11_58_35

**Review by TDu — APPROVED** [review]
Ok, great I must have had a miss configuration. Looks good to me

**Review by ivantodorovich — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
This should go to OCA/mail instead.

**Comment by Kimkhoi3010** [comment]
@pedrobaeza, I updated by your comments, and created a new PR [OCA/mail#9](https://github.com/OCA/mail/pull/9) to OCA/mail.
(This PR was closed after I create new PR to OCA/mail)

**Pull request closed without merging**
