### PR TITLE
[FIX] email_template_qweb: get translations working

### PR DESCRIPTION
**Pull request by sebalix**
Translations were broken, things hav changed in 14.0 and we need to call `_classify_per_lang` method to get the right lang, and use it to render the content.

### CODE REVIEW

**Review by TDu — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please rebase and fix pre-commit

**Comment by sebalix** [comment]
@pedrobaeza sorry for being late, PR rebased
<s>EDIT: checking pre-commit issue</s> fixed

**Pull request merged**
