### PR TITLE
[15.0][FIX] mail_show_follower: More models to exclude

### PR DESCRIPTION
**Pull request by pedrobaeza**
Slides and forums are also places where you don't want to show the recipients.

@Tecnativa TT51474

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]

**Review by victoralmau — APPROVED** [review]

**Comment by yostashiro** [comment]
Can you please add forum posts as well?

**Comment by pedrobaeza** [comment]
@yostashiro done.

**Review by yostashiro — APPROVED** [review]
Thank you!

**Comment by yajo** [comment]
Would it make sense to support an allow-list style? This way, the feature would be added only to allowed models.

I think that just for `project.task` would be enough in our use case (and maybe others have similar requirements).

cc @rafaelbn

**Comment by pedrobaeza** [comment]
I don't think so, as that list is way larger and growing/changing with each new module installed or migration.

**Comment by chienandalu** [comment]
What about a model flag? In practice there aren't that many models that the users use to communicate with customers, and the risks of leaking recipients info will show up with every new model...

**Comment by pedrobaeza** [comment]
It's still the same: when a new module containing models with threads is installed, you have to allow it explicitly. That's not what usually users wanting this feature wants to have it.

I still think the exclude model one is the correct here, and without flags, but static model name list, so you don't need to install the modules in your DB to have that list populated, like now.

**Comment by yajo** [comment]
OK, let's keep it like this. If time proves the contrary, it can be added later anyway.

**Pull request merged**
