### PR TITLE
[15.0][MIG] mail_restrict_follower_selection: Migration to 15.0

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
@qrtl

### CODE REVIEW

**Review by yostashiro — APPROVED** [review]
Tested locally.  Works as expected. 👍

**Review by DavidJForgeFlow — APPROVED** [review]
LGTM!

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Comment by LoisRForgeFlow** [comment]
@AungKoKoLin1997 Could you have a look at the CI issues?

**Comment by AungKoKoLin1997** [comment]
@LoisRForgeFlow  I solved CI issues. Do I need to squash commit for removing en.po commit?

**Comment by LoisRForgeFlow** [comment]
> @LoisRForgeFlow I solved CI issues. Do I need to squash commit for removing en.po commit?

Thanks!

@etobella one more try?

**Pull request merged**
