### PR TITLE
[16.0][MIG] mass_mailing_custom_unsubscribe: Migration to version 16.0

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
TT44333
@Tecnativa

### CODE REVIEW

**Comment by pilarvargas-tecnativa** [comment]
Functionally it should be OK but the tests still need to be checked.

**Comment by pilarvargas-tecnativa** [comment]
@carolinafernandez-tecnativa mark this as ready for review.

**Comment by pilarvargas-tecnativa** [comment]
@carolinafernandez-tecnativa take a look please :D

**Comment by pilarvargas-tecnativa** [comment]
@CarlosRoca13 @chienandalu please review

**Comment by carolinafernandez-tecnativa** [comment]
Please squash administrative commits

**Review by CarlosRoca13 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
You have to take care with the commit history squashing. You can't squash a README.rst update with a translation update:

https://github.com/OCA/social/pull/1315/commits/20d313c5aafdd346f61d6bd9e33276511e3921e0

You can alter the order of the commits to squash that commit with the one generating it. Please review again the merge guide:

https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

**Review by pedrobaeza — APPROVED** [review]
Let's not be picky with the commit history this time. Please take it into account for next occasions.

/ocabot merge nobump

**Pull request merged**
