### PR TITLE
[16.0][MIG] mail_tracking: Migration to 16.0

### PR DESCRIPTION
**Pull request by payen000**

### CODE REVIEW

**Comment by rvalyi** [comment]
hello @payen000 thank you for the work, but please you should follow the migration guidelines here https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0  Could you re-do the PR properly please?

**Comment by payen000** [comment]
Hello @rvalyi,

Thank you for your comment, I'll be checking the guidelines and applying the relevant changes soon :+1:

**Comment by rvalyi** [comment]
> Hello @rvalyi,
> 
> Thank you for your comment, I'll be checking the guidelines and applying the relevant changes soon +1

You may also want to try with this tool https://github.com/OCA/odoo-module-migrator It does enforce the guidelines and makes everything easier.

**Comment by astirpe** [comment]
There is already https://github.com/OCA/social/pull/1091

**Comment by payen000** [comment]
> There is already #1091

Thank you @astirpe, I will contribute to that PR instead.

**Comment by payen000** [comment]
> > Hello @rvalyi,
> > Thank you for your comment, I'll be checking the guidelines and applying the relevant changes soon +1
> 
> You may also want to try with this tool https://github.com/OCA/odoo-module-migrator It does enforce the guidelines and makes everything easier.

Thank you for the help @rvalyi, I was not aware of the existing migration for this module when I created this PR, so I will be contributing there instead.

**Pull request closed without merging**
