### PR TITLE
[14.0][MIG]mail_partner_opt_out: Migration to 14.0

### PR DESCRIPTION
**Pull request by GuillemCForgeFlow**
@ForgeFlow 
Changed module structure, removed field that was added to the res.partner module. Instead, inherited the mail.thread.blacklist and made a new method that adds the partner's email to the blacklist.
Before these changes, there were appearing a checkbox and a ban, two options that were doing the same once the email was added to the blacklist (see the attach file).
image
Now, if the email is not added on the blacklist a plus symbol is shown, once clicked the email is added and then the standard odoo implementation appears (a red ban, that once clicked removes the email from the blacklist).
image

### CODE REVIEW

**Comment by FernandoRomera** [comment]
@sbidoul 
At runboat show this message:
WARNING b01083c86-92d5-4b1e-82e6-df704cdd9105 odoo.addons.base_search_fuzzy.models.trgm_index: To use pg_trgm you have to create the extension pg_trgm in your database or you have to be the superuser.
Is this due to the new system?

**Comment by sbidoul** [comment]
Oh, I just reallized that by default Odoo creates de database based on template0 instead of template1. That is a weird default. Bug tracked in https://github.com/sbidoul/runboat/issues/35.

**Comment by AntoniRomera** [comment]
@GuillemCForgeFlow Can you rebuild?

**Comment by GuillemCForgeFlow** [comment]
> @GuillemCForgeFlow Can you rebuild?

Done!

**Comment by FernandoRomera** [comment]
sbidoul commented:
[There is currently no way to reinitialize a build (tracked in #34), so you need to push a commit.](https://github.com/sbidoul/runboat/issues/32#issuecomment-987663161)

**Comment by GuillemCForgeFlow** [comment]
> sbidoul commented: [There is currently no way to reinitialize a build (tracked in #34), so you need to push a commit.](https://github.com/sbidoul/runboat/issues/32#issuecomment-987663161)

Done it, but it still doesn't work...

**Comment by sbidoul** [comment]
@GuillemCForgeFlow this time it was due to an expired certificate. I clicked reset on the build.

**Comment by FernandoRomera** [comment]
@sbidoul:
At runboat show this message:
File "/opt/odoo-venv/lib/python3.6/site-packages/odoo/addons/base_search_fuzzy/models/trgm_index.py", line 131, in create_index
    _("The pg_trgm extension does not exists or cannot be installed.")
odoo.exceptions.UserError: The pg_trgm extension does not exists or cannot be installed.

**Comment by sbidoul** [comment]
> The pg_trgm extension does not exists or cannot be installed

Hm, I thought I had fixed that but I goofed somewhere apparently. It is [fixed](https://github.com/sbidoul/runboat/commit/3424f418b0bf2d40767a559490b1a6ba95b46bcb) for good, now!
Since we now have the reset button, I clicked it and its now green. I'll let you click on start to test if the instance works as expected.

**Comment by GuillemCForgeFlow** [comment]
> > The pg_trgm extension does not exists or cannot be installed
> 
> Hm, I thought I had fixed that but I goofed somewhere apparently. It is [fixed](https://github.com/sbidoul/runboat/commit/3424f418b0bf2d40767a559490b1a6ba95b46bcb) for good, now! Since we now have the reset button, I clicked it and its now green. I'll let you click on start to test if the instance works as expected.

Now the instance works, but travis fails. Any idea on how to fix it?

**Comment by FernandoRomera** [comment]
@sbidoul 
Tarvis fail, another time it was due to an expired certificate. It show:
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),)': /oca-simple-and-pypi/odoo-test-helper/

**Comment by sbidoul** [comment]
@FernandoRomera the certificate was renewed yesterday at about 2pm, so it should be ok now.

**Review by AntoniRomera — APPROVED** [review]

**Review by FernandoRomera — APPROVED** [review]

**Comment by FernandoRomera** [comment]
> @FernandoRomera the certificate was renewed yesterday at about 2pm, so it should be ok now.

Thanks.

**Comment by GuillemCForgeFlow** [comment]
Squashed two last commits.

**Comment by FernandoRomera** [comment]
@sbidoul
thanks to you, everything is ok, can you merge the pr?

**Review by MRomeera — APPROVED** [review]

**Comment by FernandoRomera** [comment]
@dreispt 
Can you merge this PR?.

**Pull request merged**
