### PR TITLE
[16.0][MIG] mail_tracking_mass_mailing: Migration to 16.0

### PR DESCRIPTION
**Pull request by nguyenhk99**
Depend on:
* #1091

### CODE REVIEW

**Comment by rafaelbn** [comment]
@nguyenhk99 dependency is merged in https://github.com/OCA/social/pull/1216

So please could review , rebase and check it? 👍🏼

**Comment by tobru** [comment]
I gave this PR a try in an Odoo 16 test environment and so far, it looks good, works as expected.

**Comment by pedrobaeza** [comment]
Superseded by #1248

**Pull request closed without merging**
