### PR TITLE
[12.0][ADD] create module mail_header_notified_partner

### PR DESCRIPTION
**Pull request by Tonow-c2c**
Result: 
image

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But this is what `mail_tracking` does...

**Comment by rafaelbn** [comment]
I think mail_tracking module is "The hidden diamond" When C2C discover it... will use every where :thinking:

**Comment by Tonow-c2c** [comment]
@pedrobaeza not exactly in this case the recipients list is in the mail.message body so we keep this trace after forwarding

**Comment by Tonow-c2c** [comment]
But you right may be we should in future improve mail_tracking module to add possibility to add the recipients list in the message body

**Comment by StefanRijnhart** [comment]
Ah, so this module actually tells the recipients of the notification emails who else was notified? Maybe this module could be modified to add the header to the conjoined email itself and not in the body as it is displayed in the thread so as not to overlap with `mail_tracking` which is really great by itself indeed.

**Comment by len-foss** [comment]
We are also interested in having this module, which is a bit orthogonal to what mail_tracking does.
It is also essentially the same as the older [mail_footer_notified_partners](https://github.com/OCA/social/tree/8.0/mail_footer_notified_partners).
Or should it be added as a checkbox "show notified followers in email" feature to mail_tracking?

**Comment by pedrobaeza** [comment]
I think it can be a system/company parameter in `mail_tracking`, and traversing not in the body, but at sending time (as it also depends on the recipient) as @StefanRijnhart commented is the right way - similar to what is done with mail.notification QWeb template in sales order/invoice.

For a simpler solution, `mail_footer_notified_partners` should be migrated instead (there are some migration PRs right there).

**Comment by len-foss** [comment]
@pedrobaeza 
You're right, and it also saw some renewed interest... I'll test that version then, and will see later if I can squeeze that feature in mail_tracking. Cheers!

**Pull request closed without merging**
