### PR TITLE
16.0[MIG] base_search_mail_content

### PR DESCRIPTION
**Pull request by anddago78**
This module adds the capability to find on any object (e.g. project issues or
helpdesk ticket) based on the conversation threads associated to them.

MT-3086 @moduon @rafaelbn @yajo @Shide  please reviews :)

### CODE REVIEW

**Review by Shide — CHANGES_REQUESTED** [review]
I'm not able to search on `message_content` field (the one that adds this module) on any view.

The option to search should appear on the bottom of the search filters.

mc

**Comment by anddago78** [comment]
HI @Shide there was a fields_view_get function that has been deprecated in the version 16 , i have changed this function with another function and now work correctly, thanks for your comments...

**Comment by pedrobaeza** [comment]
You should check #1154

**Review by Shide — APPROVED** [review]
Tested and works fine

**Review by yajo — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
