### PR TITLE
[MIG] mail_restrict_follower_selection: Migration to 15.0

### PR DESCRIPTION
**Pull request by rjpathan**

### CODE REVIEW

**Review by Shide — APPROVED** [review]
Tested on Runboat
LGTM

**Comment by etobella** [comment]
Some commits are missing, like https://github.com/OCA/social/pull/823/commits/4ffbaf492657a149798a22b60578b535256014ff or https://github.com/OCA/social/pull/823/commits/cdc6f5b1c4321f23df6ab9ee3b259de61b7bc1e2
Can you recheck all using the following PR? https://github.com/OCA/social/pull/823

**Comment by etobella** [comment]
Some commits are missing, like https://github.com/OCA/social/commit/4ffbaf492657a149798a22b60578b535256014ff or https://github.com/OCA/social/commit/cdc6f5b1c4321f23df6ab9ee3b259de61b7bc1e2
Can you recheck all using the following PR? https://github.com/OCA/social/pull/823

**Pull request closed without merging**
