### PR TITLE
[16.0][MIG] mail_inline_css: Migrate to version 16.0

### PR DESCRIPTION
**Pull request by sonhd91**
Depended on:
* https://github.com/OCA/social/pull/1111

### CODE REVIEW

**Review by simahawk — COMMENTED** [review]
LG pls drop the test dep

**Comment by sonhd91** [comment]
> LG pls drop the test dep

Droped `test-requirements.txt`, please checked again

**Review by simahawk — APPROVED** [review]

**Comment by sonhd91** [comment]
@simahawk can you merge it ?

**Comment by StephaneMangin** [comment]
Hi @sonhd91 Could you rebase your PR please ? It blocks the merge.

**Comment by sonhd91** [comment]
> Hi @sonhd91 Could you rebase your PR please ? It blocks the merge.

Okay

**Pull request merged**
