### PR TITLE
14.0 mig mail_preview_audio

### PR DESCRIPTION
**Pull request by pedroguirao**

### CODE REVIEW

**Comment by etobella** [comment]
Can you squash the last two commits?

**Comment by etobella** [comment]
The same for the two commits for pre-commit (you should use the second commit description)

**Comment by pedroguirao** [comment]
> The same for the two commits for pre-commit (you should use the second commit description)

Sorry for the delay @etobella , it's ok now?

**Comment by etobella** [comment]
Can you rename the commit for `[MIG] mail_preview_audio: Migration to 14.0`

You can do it with git commit --amend and editing the commit message. You removed the pre-commit commit, but it is not blocking from my side.

**Comment by pedroguirao** [comment]
Thx!

**Review by etobella — APPROVED** [review]

**Review by albariera — APPROVED** [review]
LGMT :+1:

**Review by olgamarcocb — APPROVED** [review]
LGTM :+1:

**Pull request merged**
