### PR TITLE
[10.0][ADD] mail_outbound_static: Allow configuration of "from" in email header

### PR DESCRIPTION
**Pull request by pepetreshere**
A backport of mail_outbound_static from v12 to v10, it eases the sending of emails from a fixed "from" address to comply with  DMARC conformity, use it when your emails can't be sent from Odoo due to invalid "from" address.

The module is very usfefull as [the fix in the Odoo stable version](https://github.com/odoo/odoo/pull/20911) has not being accepted yet.

Compared to v12, this module adds the feature to allow to setup the "from" address in the server conf file (usually odoo.conf), which is also a valid way for Odoo to setup outgoing email servers.

This work is also inspired on previous work on the closed PR https://github.com/OCA/social/pull/195.

### CODE REVIEW

**Comment by etobella** [comment]
Travis error is related to premailer #570 created that will probably solve your issue...

**Comment by etobella** [comment]
Remove the merge commits and translate the commit messages to english, please.
Also, you have lost all the history of commits, change it in order to restore this commits.
You should follow the migration guidelines (changing the order of the branches) in order to restore them

**Comment by etobella** [comment]
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

**Comment by pepetreshere** [comment]
Hello @etobella, we will try it

> Remove the merge commits and translate the commit messages to english, please.
> Also, you have lost all the history of commits, change it in order to restore this commits.
> You should follow the migration guidelines (changing the order of the branches) in order to restore them

**Comment by pepetreshere** [comment]
Closing the PR in favor of https://github.com/OCA/social/pull/573/files

**Pull request closed without merging**
