### PR TITLE
[15.0] [MIG] mail_send_copy

### PR DESCRIPTION
**Pull request by nilshamerlinck**
No change needed.

### CODE REVIEW

**Review by cyrilmanuel — APPROVED** [review]

**Review by legalsylvain — APPROVED** [review]
Thanks for porting this module.

Diff review / no test. :+1:

**Comment by legalsylvain** [comment]
hi @maintainers : is it possible to merge this approved PR ?

**Comment by OSevangelist** [comment]
@fkantelberg would you mind to check this briefly @legalsylvain @nilshamerlinck if you don't mind i would issue the OCABOT thenafter to get this merged

**Comment by legalsylvain** [comment]
Trivial Diff review. It's OK for me. maybe you should reopen the PR to have the possibility to merge it.
Thanks !

**Comment by fkantelberg** [comment]
@OSevangelist you can merge it but it might need a rebase.

**Comment by OSevangelist** [comment]
@fkantelberg can you help on what exactly went wrong here. I must admit the explanation on using the ocabot with this scenario is not all to selfexplicatory ;-)

**Comment by OSevangelist** [comment]
@legalsylvain are you someswhat convinced that reopening will do the trick ?

**Comment by legalsylvain** [comment]
> @legalsylvain are you someswhat convinced that reopening will do the trick ?

yes. reopen (or create a new PR) + rebase should do the job.

**Comment by OSevangelist** [comment]
ok thanks @legalsylvain we will open another PR tomorrow and rebase it. I discussed that with @fkantelberg briefly he will do that tomorrow morning and i will merge it throughout the day. Thanks for the help

**Pull request closed without merging**
