### PR TITLE
[14.0][ADD] mass_mailing_contact_unique

### PR DESCRIPTION
**Pull request by ivantodorovich**
Prevent duplicate email addresses in mass mailing contacts.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't this the same as https://github.com/OCA/social/tree/12.0/mass_mailing_unique ?

**Comment by ivantodorovich** [comment]
> Isn't this the same as https://github.com/OCA/social/tree/12.0/mass_mailing_unique ?

:open_mouth: indeed! I didn't see it before, thanks!

I'll migrate it instead!

it's doing slightly a bit more than what I need though. What do you think if I split it in two: `mass_mailing_contact_unique` and `mass_mailing_list_unique` ?

**Comment by pedrobaeza** [comment]
Do you really think the split is needed? It's pretty basic...

**Comment by ivantodorovich** [comment]
> Do you really think the split is needed? It's pretty basic...

They're 2 different requirements IMO
But ok I keep it as is, it doesn't hurt anyways

Closing this, superseeded by https://github.com/OCA/social/pull/773

**Pull request closed without merging**
