### PR TITLE
[imp] mail_digest: fallback to default website

### PR DESCRIPTION
**Pull request by simahawk**
Depending on the request  might fail website retrieval might fail
nevertheless the website should be there to be found.
Fallback to search and use it if possible for digest' site name

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Do you have steps to reproduce the error?

**Comment by simahawk** [comment]
@pedrobaeza there's no error indeed as I'm already catching the runtime one prior to this PR ;)
What you would see w/out that try/except is:
```bash
File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 132, in _lookup
raise RuntimeError('object unbound')
RuntimeError: object unbound
```
This is just an improvement on top of that and retrieve the website if any.

Probably the most important thing here is the TODO comment: I'm not sure how this can be improved at config level.

The issue is: even if you have website you might get  internal notifications enabled on digest mode.
In this case you gonna get those notifications w/ a digest subject that will contain the site name instead of the company name.

Not a big deal but something we could address in the future possibly.

**Comment by pedrobaeza** [comment]
OK, thanks for the explanation. You know now my last request: change module version number :stuck_out_tongue_closed_eyes:

**Comment by simahawk** [comment]
hehe, was waiting for that. Done ;)

**Review by pedrobaeza — APPROVED** [review]

**Review by yajo — APPROVED** [review]

**Pull request merged**
