### PR TITLE
[13.0] [MIG] mass_mailing_custom_unsubscribe: Migration to v13.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT19775

### CODE REVIEW

**Comment by CarlosRoca13** [comment]
Please @ernestotejeda @chienandalu, can you review this?

**Review by chienandalu — APPROVED** [review]
Thanks @CarlosRoca13 LGTM (no much functional test is possible in runbot, anyway...)

**Comment by pedrobaeza** [comment]
I would say that you can check the mail.message emitted by the mass mailing with the footer, and click the link to check if it works.

**Comment by chienandalu** [comment]
> I would say that you can check the mail.message emitted by the mass mailing with the footer, and click the link to check if it works.

I'm afraid the token is injected later:
image

**Comment by pedrobaeza** [comment]
Ah, OK, so the only possible one is having an SMTP fake/real server.

**Review by ernestotejeda — COMMENTED** [review]
Code review: :+1:

**Review by ernestotejeda — APPROVED** [review]
Functional review: :+1:

**Pull request merged**
