### PR TITLE
[IMP] mail_tracking{,_mailgun}: process sent events and fix wrong failure event mappings... and refactor

### PR DESCRIPTION
**Pull request by yajo**
FW-port https://github.com/OCA/social/pull/787.

@Tecnativa TT32365

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Tested on own instance

**Review by chienandalu — APPROVED** [review]
:+1:

**Comment by HviorForgeFlow** [comment]
Post-migration script seems wrong @Yajo @pedrobaeza 
```
2021-11-25 11:17:35,608 1 ERROR test OpenUpgrade: mail_tracking_mailgun: error in migration script mail_tracking_mailgun/migrations/13.0.2.0.0/post-migration.py: create() missing 1 required positional argument: 'vals_list' 
2021-11-25 11:17:35,608 1 ERROR test OpenUpgrade: create() missing 1 required positional argument: 'vals_list' 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/openupgradelib/openupgrade.py", line 1876, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/auto/addons/mail_tracking_mailgun/migrations/13.0.2.0.0/post-migration.py", line 18, in migrate
    settings = env["res.config.settings"].create()
TypeError: create() missing 1 required positional argument: 'vals_list'
2021-11-25 11:17:35,617 1 WARNING test odoo.modules.loading: Transient module states were reset 
2021-11-25 11:17:35,617 1 ERROR test odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 424, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 230, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/opt/odoo/custom/src/odoo/odoo/modules/migration.py", line 180, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.6/site-packages/openupgradelib/openupgrade.py", line 1876, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/auto/addons/mail_tracking_mailgun/migrations/13.0.2.0.0/post-migration.py", line 18, in migrate
    settings = env["res.config.settings"].create()
TypeError: create() missing 1 required positional argument: 'vals_list'
2021-11-25 11:17:35,617 1 CRITICAL test odoo.service.server: Failed to initialize database `prod`. 
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/service/server.py", line 1192, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 424, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 230, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/opt/odoo/custom/src/odoo/odoo/modules/migration.py", line 180, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.6/site-packages/openupgradelib/openupgrade.py", line 1876, in wrapped_function
    if use_env2 else cr, version)
  File "/opt/odoo/auto/addons/mail_tracking_mailgun/migrations/13.0.2.0.0/post-migration.py", line 18, in migrate
    settings = env["res.config.settings"].create()
TypeError: create() missing 1 required positional argument: 'vals_list'
2021-11-25 11:17:35,618 1 INFO test odoo.service.server: Stopping gracefully 
```

**Pull request merged**
