### PR TITLE
[mail_activity_done] set activities as inactive when they have been completed.

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by AdriaGForgeFlow — APPROVED** [review]

**Comment by hbrunn** [comment]
@jbeficent please squash your commits and call your hook in the tests

**Comment by aitorbouzas** [comment]
@hbrunn @jbeficent added tests in a PR to forked repo: https://github.com/Eficent/social/pull/3

**Comment by aitorbouzas** [comment]
"Connection to the database failed" in Travis

**Comment by MiquelRForgeFlow** [comment]
@aitorbouzas solved.

@hbrunn please, remove "needs tests" tag

**Pull request merged**
