### PR TITLE
[16.0][MIG] mail_activity_done: Migration to 16.0

### PR DESCRIPTION
**Pull request by amkarthik**
This is a continuation of https://github.com/OCA/social/pull/1059 and it contains a fix reported on the parent pull request.

### CODE REVIEW

**Comment by amkarthik** [comment]
@ignissak @CasVissers-360ERP

**Review by CasVissers-360ERP — APPROVED** [review]
Nice! Reviewed and working properly now, thanks!

**Comment by rven** [comment]
What about this change?
https://github.com/OCA/social/pull/1011
to remove the ugly monkey patching part

**Comment by amkarthik** [comment]
@rven 
https://github.com/OCA/social/pull/1011 is not yet merged.
I am planning to update it here once it is merged there.

**Review by dariodelzozzo — APPROVED** [review]

**Comment by llabusch93** [comment]
Hello,

why was this approved now? I did test it and it does not work...

**Comment by CasVissers-360ERP** [comment]
@llabusch93 what is not working?

**Comment by llabusch93** [comment]
@CasVissers-360ERP 

I apologize for my previous response. It seems I misunderstood the functionality of the module. Upon further investigation, I discovered that the module does indeed serve the intended purpose. Although I initially expected the activity to be displayed as an object in the chatter, it appears that the module primarily allows users to access completed activities through the technical menu.

Please disregard my previous remarks. The module works as intended.

Thank you and apologies for any confusion caused.

Cheers

**Comment by StefanRijnhart** [comment]
@amkarthik It does look like https://github.com/OCA/social/pull/1011 is a huge improvement over the monkeypatch. Realistically, it's not going to be merged anymore in that old release. Introducing it in a new release seems more appropriate to be honest. Please review that PR and include it here if you think it's any good.

**Comment by dariodelzozzo** [comment]
@amkarthik News about this PR?

Can you include the improvement mentioned by @StefanRijnhart?

> @amkarthik It does look like https://github.com/OCA/social/pull/1011 is a huge improvement over the monkeypatch. Realistically, it's not going to be merged anymore in that old release. Introducing it in a new release seems more appropriate to be honest. Please review that PR and include it here if you think it's any good.

**Comment by StefanRijnhart** [comment]
@amkarthik OK, let's continue without the improvement from #1011. I'll prepare a PR for when this is merged. Can you squash the bugfixing commits into the migration commit to make this one ready for merge?

**Comment by amkarthik** [comment]
@StefanRijnhart Squashed the bug fix commits.

**Review by StefanRijnhart — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Thanks!

/ocabot merge nobump

**Comment by StefanRijnhart** [comment]
@dariodelzozzo @rven @hbrunn https://github.com/OCA/social/pull/1214 is ready for review.

**Pull request merged**
