### PR TITLE
[8.0][website_mail_snippet_fixed] Fixed-Width Layout Snippets for Writing Emails

### PR DESCRIPTION
**Pull request by yajo**
This module extends the functionality of the website mail designer with new
snippets with a fixed-width layout that works fine across any mail client,
including MS Outlook.

This is due to the inability to fix the known issues from module `website_mail_snippet_responsive`.

@dgzurita @rafaelbn

### CODE REVIEW

**Comment by rafaelbn** [comment]
Great, thanks :+1:

**Comment by yajo** [comment]
captura de pantalla de 2016-02-24 16-24-40

I'm pretty sure Coveralls is being too restrictive this time :laughing:

**Comment by dgzurita** [comment]
Tested in runbot :+1:

**Comment by rafaelbn** [comment]
"This branch has conflicts that must be resolved" please fix, thanks.

**Comment by yajo** [comment]
Sorry, I mixed this with another PR. Fixed now.

**Comment by rafaelbn** [comment]
Travis and runbot fails

**Comment by yajo** [comment]
Let's see now

**Comment by rafaelbn** [comment]
Perfect! all :green_apple:  :+1:

**Comment by dgzurita** [comment]
Reviewed and tested :+1:

**Comment by carlosdauden** [comment]
:+1:

**Pull request merged**
