### PR TITLE
[FIX] Make sequence of view higher than the original view

### PR DESCRIPTION
**Pull request by lfreeke**
Add a higher priority to the view.

### CODE REVIEW

**Comment by lfreeke** [comment]
Ping @hbrunn

**Comment by pedrobaeza** [comment]
What is the reasoning behind this change?

**Comment by hbrunn** [comment]
for whatever reasons, the mail module's view has priority 20: https://github.com/OCA/OCB/blob/8.0/addons/mail/mail_message_view.xml#L8

So without the patch, the custom view for the action wins in cases where no view is explicitly given, which is most places. This makes this module combine badly with others that modify the original view.

:+1: from my side

**Comment by pedrobaeza** [comment]
:+1:

**Comment by guewen** [comment]
:+1:

**Pull request merged**
