### PR TITLE
[14.0][MIG] mail_activity_partner

### PR DESCRIPTION
**Pull request by Rad0van**
Straightforward migration.

### CODE REVIEW

**Comment by Rad0van** [comment]
@ernestotejeda , @Yajo , @victoralmau please have a look. Straightforward migration, no real changes needed. However pre-commit fails strangely on something. Thank you.

**Comment by pedrobaeza** [comment]
There's a known problem right now in pre-commit across all OCA.

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
pre-commit error should be fixed now can you try to rebuild?

**Review by JoanMForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
can we move forward @Rad0van? this is close to be merged

**Comment by Rad0van** [comment]
> can we move forward @Rad0van? this is close to be merged

@AaronHForgeFlow sure. What do I need to do? Edit: force rebuild I guess. Will try.

**Comment by AaronHForgeFlow** [comment]
great! now just squash the last two commits and it should be ready to go :)

**Comment by Rad0van** [comment]
Done. Good to go I hope.

**Comment by AaronHForgeFlow** [comment]
ping @OCA/social-maintainers

**Pull request merged**
