### PR TITLE
[16.0][MIG] mail_activity_reminder

### PR DESCRIPTION
**Pull request by sebalix**
Migration from 13.0 PR https://github.com/OCA/social/pull/1134

### CODE REVIEW

**Comment by simahawk** [comment]
@sebalix can you review https://github.com/OCA/social/pull/1134 1st?

**Review by simahawk — APPROVED** [review]

**Comment by sebalix** [comment]
cc @rousseldenis @alexey-pelykh

**Review by alexey-pelykh — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
