### PR TITLE
[13.0][MIG] mail_attach_existing_attachment

### PR DESCRIPTION
**Pull request by Rad0van**
Standard migration

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There was already https://github.com/OCA/social/pull/506. Please check the existing comments at least and we can supersede that one in that case, as the contributor is no longer my employee and he's not going to continue it.

**Comment by Rad0van** [comment]
@pedrobaeza I checked summary in #438 and it wasn't mentioned there. I couldn't find it in comments there either.

**Comment by pedrobaeza** [comment]
That doesn't mean it doesn't exist. Migration issues are not very maintained, so you should check opened PRs before. Anyway, as stated, please check comments in that PR and let's go ahead with the supersede.

**Comment by Rad0van** [comment]
> That doesn't mean it doesn't exist. Migration issues are not very maintained, so you should check opened PRs before. Anyway, as stated, please check comments in that PR and let's go ahead with the supersede.

Didn't realize that - will know next time. Will cover the comments.

**Comment by Rad0van** [comment]
@pedrobaeza, @ernestotejeda, @Tardo and @chienandalu reworked (I believe) all the comments from discontinued #506. Please review. One thing regarding headers: I put only `2015 ACSONE SA/NV` into it as that was present in original one. Please provide updated text if needed.

**Review by chienandalu — APPROVED** [review]
Tested. Thanks!

**Comment by Rad0van** [comment]
@pedrobaeza out of curiosity: what happened the on first merge attempt? I cannot see anything that was wrong or different...

**Comment by pedrobaeza** [comment]
This has happened meanwhile :wink: 

bbf98c7ddf759783123489b385536043344d41ef

**Pull request merged**
