### PR TITLE
14.0 mig mail footer notified partner

### PR DESCRIPTION
**Pull request by dreispt**
- [MIG] [10.0] mail_footer_notified_partner (#200)
- OCA Transbot updated translations from Transifex
- OCA Transbot updated translations from Transifex
- FIX mail_footer_notified_partner
- [UPD] Update mail_footer_notified_partner.pot
- [MIG] mail_footer_notified_partner: Migration to 11.0
- [IMP] notification should be at the beginning of the body indeed
- [FIX] fix travis
- [MIG] mail_footer_notified_partner: Migration to 12.0
- [MIG] mail_footer_notified_martner: add to use _notify() v12 method
- [MIG] mail_footer_notified_partner: Fix test
- [UPD] Update mail_footer_notified_partner.pot
- [UPD] README.rst
- [ADD] icon.png
- Update translation files
- Update translation files
- Translated using Weblate (French)
- [IMP] mail_footer_notified_partner: black, isort, prettier
- [MIG] mail_footer_notified_partner: Migration to 14.0

### CODE REVIEW

**Comment by cvinh** [comment]
@dreispt I did a PR on your branch here : https://github.com/ursais/social/pull/1

**Comment by tafaRU** [comment]
Hi @dreispt, are you planning to carry on this work? Otherwise I can create a new PR.
Let me know, thanks.

**Comment by cvinh** [comment]
@tafaRU I did a PR here that fixes the problems https://github.com/ursais/social/pull/1

**Comment by tafaRU** [comment]
@cvinh, thanks I see, but this is not enough to move forward. I think it's quicker open a new PR, do you agree?

**Comment by cvinh** [comment]
@tafaRU I did it here then https://github.com/OCA/social/pull/855

**Comment by tafaRU** [comment]
@dreispt @rafaelbn this PR is superseded by https://github.com/OCA/social/pull/855 Please close it.

**Comment by rafaelbn** [comment]
@dreispt @tafaRU we finally decided to use https://github.com/OCA/social/pull/862 There are several modules with similar objetives

**Comment by tafaRU** [comment]
> we finally decided to use #862 There are several modules with similar objetives

Thanks @rafaelbn for the info. Then, `mail_footer_notified_partner` will be deprecated?

**Comment by rafaelbn** [comment]
Not deprecated @tafaRU just diferent options for the "same" or similar objetive as Cyril said https://github.com/OCA/social/pull/855#issuecomment-1068256758

**Pull request closed without merging**
