### PR TITLE
[13.0] [MIG] mail_full_expand: Module migrated in v13.

### PR DESCRIPTION
**Pull request by Chandresh-SerpentCS**

### CODE REVIEW

**Comment by Chandresh-SerpentCS** [comment]
Depends on #637

**Comment by bodedra** [comment]
@Chandresh-SerpentCS Can you run pre-commit?

This PR depends on ["mail", "web"], not mail_debrand. Correct?

**Comment by Chandresh-SerpentCS** [comment]
@bodedra Travis is failing in this PR due to mail_debrand module. That's why I made #637 PR to fix Travis of mail_debrand.

**Comment by Chandresh-SerpentCS** [comment]
travis

**Comment by bodedra** [comment]
Thanks @Chandresh-SerpentCS for clarification. I have reviewed PR and approve it.

**Comment by bodedra** [comment]
@Chandresh-SerpentCS Can you run pre-commit?

**Review by bodedra — APPROVED** [review]
Functional review. :+1:

**Comment by bodedra** [comment]
@dreispt Are you available for review this?

**Review by nikul-serpentcs — APPROVED** [review]
squash last 2 commits, Otherwise code review LGTM :+1:

**Comment by bodedra** [comment]
@OCA/social-maintainers Should we merge this?

**Review by RLeeOSI — APPROVED** [review]
Looks good!

**Pull request merged**
