### PR TITLE
9.0 [mig] marketing_security_group

### PR DESCRIPTION
**Pull request by cubells**
Renaming module marketing_security_group to mass_mailing_security_group

cc @Tecnativa

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hi @cubells ,

It doesn't work. For example, demo user cannot delete it's own mass mailings.

Please review

Thanks!

**Comment by rafaelbn** [comment]
Hi @cubells ,

It doesn't work. For example, demo user cannot delete it's own mass mailings. Check image:



Please review

Thanks!

**Comment by pedrobaeza** [comment]
The branch is not correct. You have to check again your git-fu.

**Comment by cubells** [comment]
@rafaelbn 
this commit https://github.com/OCA/OCB/commit/6375a4bcf4041f898830762ac892c75ab689ce15 changes the rules.

Now user can delete his own mass_mailing campaigns if belongs to Lead Automation user group, not to marketing group.

And it works.

**Review by yajo — DISMISSED** [review]
> Renaming module marketing_security_group to mass_mailing_security_group

If you rename an addon, you need to write a migration script.

----

These 2 commits have the same message:

captura de pantalla de 2016-11-24 09-45-25

We need to have descriptive messages for commits, to know what you are doing in each of them and why. It only takes some seconds and you help all of us.

----

Your branch has conflicts:

captura de pantalla de 2016-11-24 09-45-35

Please do a rebase or merge and fix them.

Thanks 😉

**Comment by pedrobaeza** [comment]
There's no need for a migration script, but a rename in the apriori.py file in OpenUpgrade, but he knows that and will make the PR when this one is merged.

**Comment by pedrobaeza** [comment]
@cubells please check this.

**Comment by cubells** [comment]
done.

@Tecnativa

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Module renamed in OpenUpgrade in https://github.com/OCA/OpenUpgrade/commit/544f656a3300de97d08399eb5028aa088c4bf47f

**Pull request merged**
