### PR TITLE
added mail_store_outgoing

### PR DESCRIPTION
**Pull request by agent-z28**
Tested on Odoo CE 12

### CODE REVIEW

**Comment by agent-z28** [comment]
GOGOGO

**Comment by hbrunn** [comment]
please fix https://travis-ci.org/OCA/social/jobs/438404444#L575 ff

**Comment by agent-z28** [comment]
ALL CHECKS SUCCESSFULL:)

**Comment by agent-z28** [comment]
I added the tests for 100% code coverage. Ready for finalizing.

**Pull request closed without merging**
