### PR TITLE
[13.0][MIG] mail_preview_base & mail_preview_audio

### PR DESCRIPTION
**Pull request by jarroyomorales**
Standard migration of mail_preview_base and mail_preview_audio

@etobella @pedrobaeza

### CODE REVIEW

**Review by etobella — CHANGES_REQUESTED** [review]
Only working when debug=assets is set, please review

**Review by etobella — APPROVED** [review]
:thinking: Now it is working without assets, seems like something is kept on memory until the debug assets is set :dizzy_face:

**Comment by jarroyomorales** [comment]
@etobella Javascript was not loading the files always in the same order and was causing an error in some cases. It should be fixed now.
I don't know if this is necessary in v12, I have never had such problem but i may cherry-pick these commits just in case.

**Comment by etobella** [comment]
@jarroyomorales I have found the same issue on 12.0, sometimes, it is not loading properly. Can you make the cherry-pick please

**Comment by jarroyomorales** [comment]
@etobella here it is https://github.com/OCA/social/pull/615

**Review by LoisRForgeFlow — APPROVED** [review]
Works nicely! :+1:

**Pull request merged**
