### PR TITLE
[10.0][ADD] {google,fetchmail}_gmail: OAuth for gmail servers

### PR DESCRIPTION
**Pull request by yankinmax**
This is a backport of Odoo SA commit https://github.com/odoo/odoo/commit/336c9aab3619abb5bfbeb07f87ae014facdefb0b
This PR is opened in order to resolve an issue https://github.com/OCA/social/issues/860
The way `ir.mail_server` creates smtp connection in v10 differ from v12. That require a complete override of the `connect` and `send_email` methods. But, I'm sure my implementation isn't the best one, and therefore not tested for the moment of PR open Help is highly appreciated to override it correctly.

### CODE REVIEW

**Comment by yankinmax** [comment]
though we have compatible with python2.7 `premailer==3.6.2` in requirements https://github.com/OCA/social/blob/f32e179fee58afc27c450c9201b66f31c38ef38d/requirements.txt#L1
runbot is installing last version which doesn't support python2.7
```
Collecting premailer
  Downloading premailer-3.10.0-py2.py3-none-any.whl
```

**Comment by PatosMarco** [comment]
what is the correct procedure to configure the oauth client? After entering client_id and secret, I cannot connect to my account

**Comment by PatosMarco** [comment]
the link that opens always has client_id = false in the url

**Comment by yankinmax** [comment]
@PatosMarco Features introduced in this PR weren't completely resolved, as I couldn't test a real Gmail account. If you have client_id and secret it's great, because you can finish work. I'm not sure my suggestions will be good enough without debugging on real credentials. Sorry.
Please give it a try by yourself. If you need I can give you access to update this PR to finish work. THX

**Pull request closed without merging**
