### PR TITLE
[FIX] mail_show_follower: Add recipients of the all related messages on the notification

### PR DESCRIPTION
**Pull request by Shide**
When using composer, doesn't include all recipients of the message on the notification.

This PR adds all the realted recipients to the notification message: Search by the `message_id` and adds all the `recipient_ids` to the notification message.

MT-547 @modouon

### CODE REVIEW

**Comment by Shide** [comment]
@HaraldPanten @ValentinVinagre @Yajo @rafaelbn test and review if you want :)

**Review by rafaelbn — APPROVED** [review]
Fine 👍

**Review by yajo — APPROVED** [review]
I'd love to see a test here.

**Pull request merged**
