### PR TITLE
[17.0][MIG] mail_optional_follower_notification: Migration to 17.0

### PR DESCRIPTION
**Pull request by ghost**
Superseeding https://github.com/OCA/social/pull/1303

### CODE REVIEW

**Comment by AndrzejGerasimukARCHIMEDES** [comment]
hello 
when we can expect that migration will be done?

**Comment by AndrzejGerasimukARCHIMEDES** [comment]
@jdidderen-nsi @pedrobaeza Is there any possibility to migration this module to 17.0 ?

**Comment by pedrobaeza** [comment]
You can start reviewing current migration to see if it's correct. OCA flows require to have two approvals (one of them being PSC).

**Review by maciej-wichowski — APPROVED** [review]
Functional and code review :+1:

**Review by AndrzejGerasimukARCHIMEDES — APPROVED** [review]

**Comment by Paulius11** [comment]
What seems to be the issue here? The runboat/build status appears to be Pending.

**Comment by ghost** [comment]
@Paulius11 I forced the update. It's good to go now 👍

**Comment by Paulius11** [comment]
Do all tests need to pass for this to be merged?

**Comment by ghost** [comment]
@OCA/social-maintainers Can you take a look at this PR and see if it can be merged ?

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
