### PR TITLE
[ADD] Adds mail_thread_track_x2many module.

### PR DESCRIPTION
**Pull request by daramousk**
Mail thread does not do a good job tracking changes on x2many fields, this
module fixes that.

### CODE REVIEW

**Comment by daramousk** [comment]
@hbrunn On `one2many` fields that are changed from outside the form, their changes are not shown on the chatter (since the write is not invoked) yet they are shown when the `read` returns. I fixed this using `message_post` on the specific places that I want the update to be shown. Perhaps there is a better solution? Or that is not a bug?

**Comment by daramousk** [comment]
@hbrunn The tests have been added quite some time back, things break here but it does not seem it is the fault of this module.

**Comment by hbrunn** [comment]
https://travis-ci.org/OCA/social/jobs/509924640#L1832 looks very much like a problem in the tests

**Comment by daramousk** [comment]
`mail_thread` should exist at that point, I specifically declare a dependency on `mail`.

**Comment by hbrunn** [comment]
mail_thread is an abstract model that doesn't have a table

**Pull request closed without merging**
