### PR TITLE
[FIX] - notify_followers has no effect in mail_optional_follower_notification

### LINKED ISSUE #499: [12.0][Mail optional follower notification] - notify_followers has no effect
This bug can be reproduced on runbot.

1. Open partner form
2. Click on send message in the chatter
3. Open the message composer
4. Un-Check "Followers of the document and", a warning message will show saying that " Followers will not be notified"
5. Add a contact to notify

6. Send
7. Go to Settings/Technical/Emails

8. All followers are set as destination for the email created

CC/ @gva-acsone

### PR DESCRIPTION
**Pull request by sbejaoui**
fixes: #499

### CODE REVIEW

**Comment by sbejaoui** [comment]
cc/ @gva-acsone

**Review by gva-acsone — APPROVED** [review]
LGTM ! Functional test +1

**Review by fuentes73 — APPROVED** [review]

**Comment by gralet** [comment]
Hello, any idea when the PR will be merged ?    Thanks

**Comment by sbejaoui** [comment]
@OCA/core-maintainers , This PR is ready to merge

**Pull request merged**
