### PR TITLE
14.0 mig mail quoted reply

### PR DESCRIPTION
**Pull request by jonasbuchholz**
Add mail_quoted_reply and migrate to version 14.0.
Initial PR to add mail_quoted_reply module to 12.0 by @etobella: https://github.com/OCA/social/pull/705
As commented in the initial PR, this module is useful for us, so we did a migration to 14.0

### CODE REVIEW

**Comment by etobella** [comment]
Did you sign OCA CLA?

**Review by flotho — APPROVED** [review]
tested on runboat

**Comment by jonasbuchholz** [comment]
> Did you sign OCA CLA?

Not yet. Is it necessary, since this is only a migration of your module?

**Comment by etobella** [comment]
Yes, it is

**Comment by etobella** [comment]
@jonasbuchholz Did you sign the CLA?

**Comment by MiquelRForgeFlow** [comment]
Superseded by https://github.com/OCA/social/pull/921.

**Comment by MiquelRForgeFlow** [comment]
This PR should be closed.

**Pull request closed without merging**
