### PR TITLE
[13.0] Add module mail_internal_chat

### PR DESCRIPTION
**Pull request by grindtildeath**
When messages are logged on a document chatter and internal users
are tagged with `@`, the user being tagged will be notified and can answer
in a chat window.
In any case, answering in the chat window will send a message to all followers
of the document, including external partners, even if the original message was
internal and posted using the "Log a note" tab. This is not the case answering
in the Discussions app will respect the original message type.
This module adds a "Keep Chat Internal" checkbox on message subtypes to avoid
sending any message sent from the chat window to external followers.

### CODE REVIEW

**Comment by elvise** [comment]
@grindtildeath can you rebase ?

**Comment by grindtildeath** [comment]
@elvise Why is it needed? I see no conflicts with the base branch...

**Comment by elvise** [comment]
> @elvise Why is it needed? I see no conflicts with the base branch...

@grindtildeath for runboat :)

**Comment by grindtildeath** [comment]
@elvise done.

**Review by gurneyalex — APPROVED** [review]

**Comment by grindtildeath** [comment]
@OCA/social-maintainers any one to merge this small module?

**Pull request closed without merging**
