### PR TITLE
[16.0][MIG] mass_mailing_partner_contact_active

### PR DESCRIPTION
**Pull request by nguyenminhchien**

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]

**Comment by StephaneMangin** [comment]
For the PR dependency, please take in account this comment https://github.com/OCA/edi/pull/724#issuecomment-1461765822

**Comment by StephaneMangin** [comment]
@nguyenminhchien Hi, could you update your PR dependencies to go forward and validate this PR please ?

**Comment by nguyenminhchien** [comment]
> @nguyenminhchien Hi, could you update your PR dependencies to go forward and validate this PR please ?
 
@StephaneMangin  Hello, i did it 3 weeks ago 
image

**Comment by nguyenminhchien** [comment]
@StephaneMangin the tests are ok now.

**Comment by grindtildeath** [comment]
@OCA/social-maintainers Anyone to reopen this one please?

**Pull request closed without merging**
