### PR TITLE
[16.0] [MIG] mail_quoted_reply

### PR DESCRIPTION
**Pull request by Borruso**
Migration mail_quoted_reply from 14.0 to 16.0

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

### CODE REVIEW

**Comment by llabusch93** [comment]
Hello,

What is the issue here? When will this be merged?

**Comment by llabusch93** [comment]
Hello,

I just learned that the migration is not complete and it does not work, even throws errors. Is my help here wanted, or are you already take care of this?

Cheers

**Comment by llabusch93** [comment]
Hello,

I just created a PR (https://github.com/Borruso/social/pull/1) to your branch what really migrates the module. Once you merge this, this PR here could be go further in the timeline.

Cheers

**Review by sonhd91 — APPROVED** [review]
LGTM

**Comment by simahawk** [comment]
/ocabot migration mail_quoted_reply

NOTE: there are some pending fixes on v15 worth fwd.

**Comment by Borruso** [comment]
> /ocabot migration mail_quoted_reply
> 
> NOTE: there are some pending fixes on v15 worth fwd.

@simahawk can you check now?

**Comment by llabusch93** [comment]
Hello guys,

any news here?

**Review by jonasbuchholz — APPROVED** [review]

**Review by jonasbuchholz — APPROVED** [review]

**Review by grindtildeath — APPROVED** [review]
@Borruso Thanks for the mig.

Looks good to me, but can you please cherry-pick this fix? 
https://github.com/grindtildeath/social/commit/e6034d6c2d1cb991687f34ecfa00979af6fbed30

Otherwise, can someone from @OCA/social-maintainers please merge and I'll open a PR afterwards? :pray:

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

@grindtildeath ping

**Comment by rafaelbn** [comment]
It doesn't look like this command is working:

/ocabot migration mail_quoted_reply

**Pull request merged**
