### PR TITLE
[14.0][mail_footer_notified_partner] Rename module to mail_body_notified_partner

### PR DESCRIPTION
**Pull request by cvinh**
Module has been renamed from mail_footer_notify_partner to mail_body_notified_partner as the notification is in the body since v14
Moreover, I think that the notification should be in the beginning of the body indeed as I explained here https://github.com/OCA/social/pull/289#issuecomment-401576313

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hello @JonathanNEMRY @SimoRubi this is a module name change, you are contributors, can you review here please? Thank you!

**Comment by cvinh** [comment]
This module does the job https://github.com/OCA/social/pull/867
So I close this PR

**Comment by cvinh** [comment]
I reopen that PR because of discussion in https://github.com/OCA/social/pull/855

**Comment by cvinh** [comment]
Please PSC Member could you add no stale label ?
Thank you in advance

**Comment by cvinh** [comment]
Close because renaming module is here https://github.com/OCA/social/pull/855

**Pull request closed without merging**
