### PR TITLE
[ADD] mass_mailing_event_registration

### PR DESCRIPTION
**Pull request by JavierIniesta**
This module adds actions to send mass mailings and allows to add to mailing
lists from event registrations tree view.

### CODE REVIEW

**Comment by JavierIniesta** [comment]
Tests in progress

**Comment by JavierIniesta** [comment]
cc @yajo @antespi @sergio-incaser @carlos-incaser @janetrp @rafaelbn @pedrobaeza  @dreispt

**Comment by JavierIniesta** [comment]
[IMP] Tests added

**Comment by dreispt** [comment]
This is related to another existing PR, correct?

**Comment by JavierIniesta** [comment]
Related to OCA/social/pull/23

**Comment by dreispt** [comment]
According to the discussion there, shouldn't this PR be in OCA/event?

**Comment by janetrp** [comment]
@rafaelbn could you pls answer?

**Comment by rafaelbn** [comment]
```
+    'depends': [
+        'event',
+        'mass_mailing'
```

@dreispt , @pedrobaeza thinks it must be in OCA/event, I answered:
- https://github.com/OCA/social/pull/23#issuecomment-155394095
- https://github.com/OCA/social/pull/23#issuecomment-155430252

and @pedrobaeza agree to maintain it in Social here:
- https://github.com/OCA/social/pull/23#issuecomment-155434071

I maintain my opinion of OCA/social, please let me know @pedrobaeza @dreispt  what do you think please

**Comment by pedrobaeza** [comment]
It mixes both areas, so it can be either in one place or in another, but the name should reflect first the area where is hosted. If we put it in social, it must be _mass_mailing_event_registration_. If we host it in event, it must be _event_registration_mass_mailing_.

Which part is bigger/principal? I'm not really sure

**Comment by dreispt** [comment]
Not an easy call since this is quite borderline. My reasoning is:
- It adds UI features on Event objects
- Event already depends on Social (`mail`), but Social does not require Event.

So, I would say that this is adding a Mail feature to Event, rather than adding an Event feature to Mail.

**Comment by rafaelbn** [comment]
Ok, I agree as Pedro and Daniel make same reasoning. Then @JavierIniesta:
- name: event_registration_mass_mailing
- repo: OCA/Event

**Pull request closed without merging**
