### PR TITLE
[MIG][13.0] mail_activity_reminder

### PR DESCRIPTION
**Pull request by rousseldenis**
- [x] Migration
- [x] Group sendings per user and per type

### CODE REVIEW

**Comment by rousseldenis** [comment]
@alexey-pelykh I've implemented the roadmap. Do you see other things that can be done ?

**Comment by mathben** [comment]
Why this pull request is in draft? I am interested in this feature. Thanks :-)

**Comment by simahawk** [comment]
@rousseldenis ping :)

**Review by sebalix — APPROVED** [review]

**Review by alexey-pelykh — APPROVED** [review]

**Pull request merged**
