### PR TITLE
[15.0][ADD] mail_save_as_template_security

### PR DESCRIPTION
**Pull request by Tisho99**
This module allows you to restrict the "Save as new template" button to
a specific group of users in the email sender wizard form.

T-5296

### CODE REVIEW

**Comment by Tisho99** [comment]
@ValentinVinagre @HaraldPanten @luis-ron

**Review by HaraldPanten — APPROVED** [review]
Functional review.

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Comment by HaraldPanten** [comment]
@etobella @pedrobaeza do you mind give us a hand to move it forward? 🙏

THX in advance!

**Comment by pedrobaeza** [comment]
Following other patterns, I suggest you to name it `mail_save_as_template_security`.

**Review by manuelregidor — APPROVED** [review]
LGTM

**Comment by HaraldPanten** [comment]
@Tisho99 Could you apply these changes? THX!

> Following other patterns, I suggest you to name it `mail_save_as_template_security`.

**Comment by ValentinVinagre** [comment]
@pedrobaeza ,do you think it's ok to merge? @Tisho99 has made the name change.

**Pull request merged**
