### PR TITLE
[15.0][MIG] mail_preview_audio: Migration to 15.0

### PR DESCRIPTION
**Pull request by chienandalu**
- Standard migration

@Tecnativa TT41546

please review @CarlosRoca13 

ping @etobella

### CODE REVIEW

**Review by etobella — APPROVED** [review]
Tested on runbot

**Comment by pedrobaeza** [comment]
I think this is worth to be proposed to Odoo upstream to master, don't you think?

**Comment by chienandalu** [comment]
> I think this is worth to be proposed to Odoo upstream to master, don't you think?

I spent some time thinking that it was indeed added in v14 as you can preview some audio files in the core attachments widget (you can with `mp3`, but you can't with `wav`, for example) that are run in the browser's video player.

But I was missing the point of the base module that adds a field widget for binary files that allows that previews in place.

image

So the whole binary field widget should be moved to have that.

**Comment by pedrobaeza** [comment]
I don't quite get you. The idea is to use this preview option in the DMS. If not needed for most audio file (OGG, MP3, OPUS...), then let's get rid off this module. WAV is not so important IMO.

**Comment by chienandalu** [comment]
> I don't quite get you. The idea is to use this preview option in the DMS. If not needed for most audio file (OGG, MP3, OPUS...), then let's get rid off this module. WAV is not so important IMO.

`dms` has `mail_preview_base` as a dependency which adds the mentioned `preview_binary` field widget (nothing to do with core) which is extended by this module to support audio files. (https://github.com/OCA/dms/blob/0142cb1fe6ae0ee3316d493e3d3c981f881f3ef0/dms/views/dms_file.xml#L418)

What core does have already is support for audio files in the attachments widget which this module used to support as well but now delegates to Odoo.

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
