### PR TITLE
[FIX] mail_debrand: keep original styling in email footer

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Keep font size, color and newline from Odoo function.

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Odoo:

odoo

Mail debrand before this change:

debrand-before

Mail debrand after this change:

debrand-after

**Review by elicoidal — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
Please change module version number

**Comment by StefanRijnhart** [comment]
@pedrobaeza done, sorry again!

**Review by yajo — APPROVED** [review]

**Comment by yajo** [comment]
Please check travis

**Comment by StefanRijnhart** [comment]
@yajo i checked Travis and it seems unrelated to this change. The same problem (a timeout in a web test) occurs on the main branch in this job: https://travis-ci.org/OCA/social/jobs/304915249

**Comment by yajo** [comment]
Oh yes, branch 8.0 seems to be broken.

**Pull request merged**
