### PR TITLE
[12.0][MIG] mail_private

### PR DESCRIPTION
**Pull request by jarroyomorales**
Migration to 12.0 of `mail_private` @etobella

### CODE REVIEW

**Comment by gurneyalex** [comment]
I'm curious, why are the tests in a separate module?

**Comment by gurneyalex** [comment]
Also please fix the tests : travis is red.

**Comment by jarroyomorales** [comment]
@gurneyalex This missing cherry-pick is causing some incompatibilities with this module https://github.com/OCA/social/pull/581 . After it and some minor changes it should be green!

Tests are in a separated module because of the dependency of `test_mail` , an odoo core module that adds models and functionalities to test things like this more easily.

**Comment by gurneyalex** [comment]
@jarroyomorales can you rebase now that #581 is merged?

**Comment by jarroyomorales** [comment]
@gurneyalex Its green now!

**Review by gurneyalex — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
