### PR TITLE
[15.0][MIG] mass_mailing_partner

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hello @Yajo @Shide , please could you make here a review? thanks!

**Review by Shide — APPROVED** [review]
Tested and everyting it's fine

**Review by yajo — APPROVED** [review]

**Comment by yajo** [comment]
@emagdalenaC2i please rebase to see failures and fix them, so we can merge. Thanks!

**Comment by rafaelbn** [comment]
Hello @emagdalenaC2i , please could you check https://github.com/OCA/social/commits/fd58c34212f533c5aea61c00539ecb7281aefe9f ? thank you!

**Review by manuelcalerosolis — APPROVED** [review]

**Review by espo-tony — APPROVED** [review]

**Pull request merged**
