### PR TITLE
[IMP] mail_outbound_static: black, isort, prettier

### PR DESCRIPTION
**Pull request by ghost**
Let's add a contributing, so we can work better, together !

### CODE REVIEW

**Comment by yostashiro** [comment]
@romainSudokeys There is already a PR for this module: https://github.com/OCA/social/pull/645

**Comment by yostashiro** [comment]
@romainSudokeys For your future migration PRs, please also follow the steps described here: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0 😃

**Comment by ghost** [comment]
> @romainSudokeys For your future migration PRs, please also follow the steps described here: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

Thanks for your help, i will try to do my best in the futur Thank you and have a good day 
Should i have to delete my PR ?

**Comment by yostashiro** [comment]
@romainSudokeys You can simply close this PR. 😉

**Pull request closed without merging**
