### PR TITLE
[ADD] mail_quoted_reply

### PR DESCRIPTION
**Pull request by etobella**
This addon allows to reply on messages:
imagen
imagen

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I would call it `mail_quoted_reply` or similar for being more specific.

**Comment by etobella** [comment]
Sure @pedrobaeza

**Review by albariera — APPROVED** [review]
LGTM :+1:

**Review by olgamarcocb — APPROVED** [review]
:+1:

**Comment by jonasbuchholz** [comment]
@etobella We are looking for a similar function. Is there anything that speaks against migrating this module to version 14.0? I could open a new PR for that.

**Comment by etobella** [comment]
At the end we did not use the module, but feel free to open a migration 14 :smile:

**Pull request closed without merging**
