### PR TITLE
[12.0][ADD]mail_attach_existing_attachment_account

### PR DESCRIPTION
**Pull request by tbaden**
in v12.0 account has a new mail wizard form for the account module.
it's created from scratch in account, therefore no other entry point for a general solution or a possible addition to existing module mail_attach_existing_attachment.

issue: https://github.com/OCA/social/issues/375

@pedrobaeza is this the right way, to extend the existing module or more like a standalone which adds can_attach_attachment and object_attachment_ids to the new account.invoice.send model, which inherits the mail.compose.message. the second way would be kind of redundant if someone installs both modules 🤔

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This one is perfect, thanks! You can add auto_install: True in the manifest for not having to worry about installing it manually.

**Comment by tbaden** [comment]
> This one is perfect, thanks! You can add auto_install: True in the manifest for not having to worry about installing it manually.

**Comment by tbaden** [comment]
done

**Comment by tbaden** [comment]
@pedrobaeza there seems to be an issue with runbot
first: Unable to find image 'oca-social:42795b0_3' locally

and it tries to get another branch from eficent 🤔 

 Command '['git', 'clone', '-q', 'https://github.com/Eficent/social', '-b', '12.0-mig-mail_activity_board', '--single-branch', '--depth=1', '/home/odoo/dependencies/social-eficent']' returned non-zero exit status 12

how can this be resolved

**Comment by tbaden** [comment]
https://github.com/OCA/social/blob/66bb112d2f27b8fe902b352f89569782e043c6f3/oca_dependencies.txt#L3

but the branch does not exist anymore...
the same for travis. it fails on clone

**Comment by pedrobaeza** [comment]
Please rebase as there was an error in main branch:

https://github.com/OCA/social/commit/a0bc66bb77727cd258ba76caeb408f3e43f5f6c9

**Comment by tbaden** [comment]
thanks for the quick response. the new issue didn't even stand a chance.

**Review by cfreyse — APPROVED** [review]

**Review by alexschubert — APPROVED** [review]
Thanks for your contribution.

Functional testing was successful.

**Pull request merged**
