### PR TITLE
[11.0][ADD] mail_edit

### PR DESCRIPTION
**Pull request by jarroyomorales**
Mail Edit
=================
This module allows you to edit chatter messages while keeping track of
the previous editions.

Usage
=====
On the messages you are allowed to edit, a new icon will appear. After
clicking it a view will open where you will be able to change the content.
For already edited messages, an edited label will be visible and by clicking on
it you will be able to see comments before the modifications.

image

### CODE REVIEW

**Comment by hbrunn** [comment]
did you look into migrating https://github.com/OCA/social/tree/8.0/mail_edit ?

**Comment by jarroyomorales** [comment]
@hbrunn I looked at that module but I havent worked on 8.0 and I found there was a big gap between 8 and 11. I thought it was easier for to start again but I can try to add the feature of moving mails from records here.

**Comment by hbrunn** [comment]
it's fine to do a complete rewrite if technically necessary. But you should keep the same name, otherwise we'll need extra work in migrations

**Comment by jarroyomorales** [comment]
@hbrunn Name changed!

**Comment by MrTango** [comment]
is there any reason to not merge this?

**Review by etobella — APPROVED** [review]

**Review by HviorForgeFlow — COMMENTED** [review]
I could not test the module in runbot. Anytime I try to Send a Message on a chatter this error raises:
```
Error:
Uncaught RangeError: Maximum call stack size exceeded

http://3442959-456-87ae87.runbot2-2.odoo-community.org/mail_edit/static/src/js/thread.js:9
Traceback:
RangeError: Maximum call stack size exceeded
    at Class.chat_manager.make_message [as _make_message_super] (http://3442959-456-87ae87.runbot2-2.odoo-community.org/mail_edit/static/src/js/thread.js:9:24)
    at Class.chat_manager.make_message [as _make_message_super] (http://3442959-456-87ae87.runbot2-2.odoo-community.org/mail_edit/static/src/js/thread.js:9:24)
    at Class.chat_manager.make_message [as _make_message_super] (http://3442959-456-87ae87.runbot2-2.odoo-community.org/mail_edit/static/src/js/thread.js:9:24)
    at Class.chat_manager.make_message [as _make_message_super] (http://3442959-456-87ae87.runbot2-2.odoo-community.org/mail_edit/static/src/js/thread.js:9:24)
    at Class.chat_manager.make_message [as _make_message_super] (http://3442959-456-87ae87.runbot2-2.odoo-community.org/mail_edit/static/src/js/thread.js:9:24)
    at Class.chat_manager.make_message [as _make_message_super] (http://3442959-456-87ae87.runbot2-2.odoo-community.org/mail_edit/static/src/js/thread.js:9:24)
    at Class.chat_manager.make_message [as _make_message_super] (http://3442959-456-87ae87.runbot2-2.odoo-community.org/mail_edit/static/src/js/thread.js:9:24)
    at Class.chat_manager.make_message [as _make_message_super] (http://3442959-456-87ae87.runbot2-2.odoo-community.org/mail_edit/static/src/js/thread.js:9:24)
    at Class.chat_manager.make_message [as _make_message_super] (http://3442959-456-87ae87.runbot2-2.odoo-community.org/mail_edit/static/src/js/thread.js:9:24)
    at Class.chat_manager.make_message [as _make_message_super] (http://3442959-456-87ae87.runbot2-2.odoo-community.org/mail_edit/static/src/js/thread.js:9:24)
```
@jarroyomorales any idea on that?

**Comment by jarroyomorales** [comment]
@HviorForgeFlow It is due to an incompatibility with `mail_tracking`, I will check!

**Pull request closed without merging**
