### PR TITLE
[MIG] mail_activity_done: Migration to 17.0

### PR DESCRIPTION
**Pull request by jaydeep32**

### CODE REVIEW

**Comment by etobella** [comment]
Can you rebase? we needed to apply a change on main branch

**Comment by hbrunn** [comment]
@jaydeep32 please fix conflicts

**Comment by jaydeep32** [comment]
Hello @hbrunn , I am solving conflicts one after the other, and there are many of them, and it is getting difficult. So is it ok if I close this PR and make a fresh one with the latest 17.0?

**Comment by hbrunn** [comment]
sure, whatever works for you

**Pull request closed without merging**
