### PR TITLE
[16.0][FIX] mail_debrand: Avoid odoo.sh links removal (url like my-customer.odoo.com )

### PR DESCRIPTION
**Pull request by myrrkel**

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]
Makes sense, thanks!

**Comment by pedrobaeza** [comment]
Please rename commit message to (including module name and avoiding long first line):

```
[FIX] mail_debrand: Avoid odoo.sh links removal

For URLs like my-customer.odoo.com
```

**Comment by myrrkel** [comment]
@pedrobaeza Done!

**Comment by pedrobaeza** [comment]
Thanks. Please do a rebase (instead of a pull) for removing the merge commit that has now appeared.

**Comment by myrrkel** [comment]
@pedrobaeza Is it better? I don't understand why a test is failing now.

**Review by pedrobaeza — APPROVED** [review]
Don't worry about the coverage. It's a glitch and it's not mandatory.

/ocabot merge patch

**Pull request merged**
