### PR TITLE
[MIG][15.0][mail_autosubscribe] Standard migration

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Review by matiasperalta1 — APPROVED** [review]

**Review by manuelregidor — APPROVED** [review]
Technical review. LGTM

**Review by HaraldPanten — APPROVED** [review]
Functional review LGTM.

I think this one could be merged @rafaelbn

**Review by loida-vm — APPROVED** [review]
Functional review. LGTM

**Review by ArantxaSudon — APPROVED** [review]
Funcional review.LGTM

**Comment by HaraldPanten** [comment]
@rafaelbn @pedrobaeza Could you merge, please?

THX!

**Pull request merged**
