### PR TITLE
[16.0][FIX] mail_composer_cc_bcc: adapt to changes upstream

### PR DESCRIPTION
**Pull request by hbrunn**
that's a nifty way to detect upstream changes and force adapting to it.

I wonder however if we couldn't achieve the same goal without copying so much code by setting some context keys that are picked up in an override of `ir.mail.server#build_email`

### CODE REVIEW

**Comment by nilshamerlinck** [comment]
hi @hbrunn 
- we took the occasion of the migration to 17.0 to get rid of this big override in https://github.com/OCA/social/pull/1312
- iirc before that we had tried an approach based on context but failed, we'll look into it again

**Review by nilshamerlinck — APPROVED** [review]

**Review by trisdoan — APPROVED** [review]

**Comment by trisdoan** [comment]
Hello @hbrunn, I just opened a PR: https://github.com/hbrunn/social/pull/4 to add another changes from upstream, would you mind taking a look?

**Comment by hbrunn** [comment]
@trisdoan thanks, merged

**Comment by yajo** [comment]
Both the previous error message and the new changes are a bit cryptic... could you please explain what was happening?

**Comment by hbrunn** [comment]
@yajo they created a [test](https://github.com/OCA/social/blob/16.0/mail_composer_cc_bcc/tests/test_mail_cc_bcc.py#L47) that compares the hash of the source code of a function they override with a list of known hashes, so as soon as this changes in upstream, the test fails and we know we have to check if we need to incorporate any changes from there.

Added an error message to this effect in f2e9624fc060

**Comment by yajo** [comment]
Ah wow! That was very non-obvious. Thanks.

Would you mind to squash it and put that explanation in the commit message itself? I think it'll be valuable some day when it happens again and we `git blame` over it.

Apart from that, the change LGTM.

**Comment by hbrunn** [comment]
added the commit message. But what do you want me to squash here? Seems like three logically independent changes to me

**Review by yajo — APPROVED** [review]
If the commits said something like "adapt to changes upstream. Changes in odoo/odoo\#123123 made the hash change", their messages would be more valuable.

If a single commit contained all those explanation, that'd be equally good to me.

But in any case, it's OK if you don't prefer to squash. At this point it's good enough to me. 😄 

Thank you very much!

/ocabot merge patch

**Pull request merged**
