### PR TITLE
[13.0] add mass_mailing_contact_active and mass_mailing_partner_contact_active

### PR DESCRIPTION
**Pull request by grindtildeath**
This PR includes two modules:

 - mass_mailing_contact_active: This module adds an active field on mailing contact and subscription.
 - mass_mailing_partner_contact_active: This module automatically triggers archive/unarchive operations on partner
to the mailing list contact and its subscriptions.

Closes: #520

### CODE REVIEW

**Review by ajaniszewska-dev — APPROVED** [review]
LG

**Review by sebalix — APPROVED** [review]
Travis failing on other addons, doesn't seem related to this PR

**Comment by grindtildeath** [comment]
@yajo @pedrobaeza Can you guys please have a look at the travis error on this PR? :pray: 

Looks like it happens only when `mass_mailing_partner` is installed before `mass_mailing_custom_unsubscribe`, and that is what is happening here with a new module depending on the former.

**Comment by pedrobaeza** [comment]
It's your module which is triggering a new write. The usual technique is:

- Add at the beginning `from odoo.tools import config`.
- On the conflicting code, add a "test condition" for seeing if it's in test mode and it's testing your module: `test_condition = config["test_enable"] and self.env.context.get("test_mass_mailing_contact_active")`
- Don't do your code `if not test_condition`.
- Add in your module tests the context `test_mass_mailing_contact_active` for testing your behavior.

**Comment by grindtildeath** [comment]
@pedrobaeza The `write` functions are not triggered during the tests of `mass_mailing_custom_unsubscribe`, but it seems that the definition of the `active` field on `mailing.contact.subscription` is breaking this test: 
```
AssertionError: The test code "odoo.__DEBUG__.services['web_tour.tour'].run('mass_mailing_custom_unsubscribe_tour_contact')" failed
Tour mass_mailing_custom_unsubscribe_tour_contact failed at step Uncheck list 1 (trigger: li:contains('test list 1') input:checked)
```
Question is, can these JS tests be fixed considering the possibility of having an  `active` field on `mailing.contact.subscription` or should we better test the modules separately :question:

**Comment by pedrobaeza** [comment]
For me it's an error to segregate modules, because they can be installed together in real installations, so the problem may appear there, but I don't want to block this.

**Comment by grindtildeath** [comment]
@pedrobaeza I did spend more than 4 hours trying to understand what's the issue, and it seems to be linked to the order of modules installation as the issue is not reproducible all the time. I unfortunately can't invest any more time, as it looks to be quite random.

**Comment by pedrobaeza** [comment]
OK, let's keep it then this way and hope that the issue is not reproduced in real environments:

/ocabot merge nobump

**Pull request merged**
