### PR TITLE
[13.0][FIX] mail_activity_board: unlink issue due to bad migration

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Fixes https://github.com/OCA/social/issues/556.

### CODE REVIEW

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by HviorForgeFlow — APPROVED** [review]

**Review by lmignon — COMMENTED** [review]
@MiquelRForgeFlow Thank you for the fix but can you add a unittest for this case.
Thanks

**Comment by MiquelRForgeFlow** [comment]
> can you add a unittest for this case.

I think it's not needed, it's just a `sudo() -> with_user()`/` SUPERUSER_ID -> is_superuser()` error. It's not a bug fix, but a regression fix due to bad migration. If the migration was done correctly, nobody would have asked to add a test.

**Review by CasVissers-360ERP — APPROVED** [review]
Thnx! 👍 Solves the issue.

**Pull request merged**
