### PR TITLE
[15.0][FIX] mail_activity_team: Fix tests

### PR DESCRIPTION
**Pull request by victoralmau**
Changes done:
- [x] `mail_activity_done`: Re-do method to make it compatible with other modules and core + Improve tests.
- [x] `mail_activity_team`: Fix tests since https://github.com/odoo/odoo/commit/d64fff459b745d247cc19d58994b9da4bd50292a
Possible improvement in:
- [x] `mail_composer_cc_bcc`: https://github.com/OCA/social/pull/1223

@Tecnativa

### CODE REVIEW

**Comment by victoralmau** [comment]
I have found a curious thing, if you installed only `mail_activity_team`, tests failed, but if you had installed `mail_activity_done` they didn't fail because that module re-defined the method completely.

I think it would be good to create a PR so that odoo builds the query in a separate method to add some extra condition in some method. What do you think @pedrobaeza ?

**Comment by pedrobaeza** [comment]
Yes, we can try to get a hook out of Odoo.

**Comment by MiquelRForgeFlow** [comment]
FYI The fix in `mail_composer_cc_bcc` was merged.

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
