### PR TITLE
[12.0][MIG] mail_optional_autofollow

### PR DESCRIPTION
**Pull request by naglis**

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Thanks! Can you apply python-black to align with https://github.com/OCA/social/pull/457?

**Comment by naglis** [comment]
@StefanRijnhart, sure, I wasn't certain if _Black_ should be applied to v12 as well, will do.

**Comment by pedrobaeza** [comment]
Unless full repository is converted to "black style", you can't apply it to an individual module, as some errors will arise like flake8 80 cols limit.

**Comment by naglis** [comment]
@pedrobaeza, I see, thanks for the comment, spared me the trouble :slightly_smiling_face:

**Comment by StefanRijnhart** [comment]
Oh, sorry. I was not aware of that!

**Review by StefanRijnhart — APPROVED** [review]

**Review by simahawk — APPROVED** [review]
LG

**Review by lmignon — APPROVED** [review]

**Pull request merged**
