### PR TITLE
[11.0][FIX] mail_drop_target: Add sudo on config_param

### PR DESCRIPTION
**Pull request by etobella**
Missing sudo on getting the parameter

@JordiBForgeFlow @JoanSForgeFlow @LoisRForgeFlow @hbrunn @jarroyomorales

### CODE REVIEW

**Review by jarroyomorales — APPROVED** [review]

**Review by bodedra — APPROVED** [review]

**Review by hbrunn — APPROVED** [review]
we'll need that in later versions too I guess

**Comment by etobella** [comment]
Don't worry, I will make the cherry pick

**Comment by etobella** [comment]
Well, 11.0 is the only merged version, and the only existing PR is #242 for 10.0

**Pull request merged**
