### PR TITLE
[15.0][ADD] mail_forward: new module to forward messages from the chatter

### PR DESCRIPTION
**Pull request by carlos-lopez-tecnativa**
TT51020
@Tecnativa @pedrobaeza @chienandalu @victoralmau could you please review this

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Should we set a FW: prefix in de subject?

image

**Comment by carlos-lopez-tecnativa** [comment]
> Should we set a FW: prefix in de subject?
> 

I added the prefix similar to Gmail. Thanks for the observation.

image

**Review by chienandalu — APPROVED** [review]

**Review by pedrobaeza — COMMENTED** [review]
Tested on runboat and working. Is there any other FA icon that represents better the forwarding (double arrow?)

**Comment by chienandalu** [comment]
> Tested on runboat and working. Is there any other FA icon that represents better the forwarding (double arrow?)

It can be done with `fa-stack`. An example: https://github.com/OCA/social/blob/92640d7d282f251576e76b00e8b77d3e3cf8e598/mail_tracking/static/src/components/discuss/discuss.xml#L78-L100

**Comment by carlos-lopez-tecnativa** [comment]
> > Tested on runboat and working. Is there any other FA icon that represents better the forwarding (double arrow?)
> 
> It can be done with `fa-stack`. An example:
> 

With your example, it looks like this
image

With `fa-forward` it looks like this. What do you think?

image

**Comment by chienandalu** [comment]
I meant stacking your original arrows. Altough the fa-forward could fit

**Comment by pedrobaeza** [comment]
I think stacking the arrow seems better

**Comment by carlos-lopez-tecnativa** [comment]
I updated the icon, and it looks like this. What do you think?
image

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
