### PR TITLE
[9.0][MIG] mail_tracking_mailgun

### PR DESCRIPTION
**Pull request by antespi**
This PR includes https://github.com/OCA/social/pull/87 in order to test it in Travis and Runbot

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You need to rebase, but as I have squashed some commits, the best bet is to make an interactive rebase in this branch, removing all the mail_tracking related commits, and then rebase against 9.0 branch.

**Comment by hbrunn** [comment]
the difference between this and the 8.0 version is https://github.com/OCA/social/pull/89/commits/5ee1b211a0669e2cd28e08b4b070d833e878e591, which looks good enough to me :+1:

**Review by lasley — APPROVED** [review]
Hard to argue with that diff 👍

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Waiting to runbot to merge.

**Pull request merged**
