### PR TITLE
[11.0][ADD] mail_activity_creator

### PR DESCRIPTION
**Pull request by jarroyomorales**
Very simple module to show who is the creator of activities since it is missing in Odoo core.

image

@etobella

### CODE REVIEW

**Review by etobella — APPROVED** [review]
LGTM :+1:

**Comment by etobella** [comment]
It can be useful when users wants to check who created the task in order to ask questions

**Review by etobella — CHANGES_REQUESTED** [review]
It is not working properly. Odoo creates activities as sudo, so, the creator is never stored properly
https://github.com/odoo/odoo/blob/11.0/addons/mail/models/mail_activity.py#L192

**Review by etobella — APPROVED** [review]
Now it works as expected. Also, a test was added showing the issue with create_uid

**Comment by jarroyomorales** [comment]
Thank you for the fix! @etobella

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by jarroyomorales** [comment]
Thank you @JordiBForgeFlow !
I think in 12.0 it is already implemented, so no migration will be necessary.

**Pull request merged**
