### PR TITLE
[MIG] mail_tracking: Migration to 16.0

### PR DESCRIPTION
**Pull request by hvgollar**

### CODE REVIEW

**Review by maq-adhoc — CHANGES_REQUESTED** [review]
When the mails fail an error appears when rendering the chatter.

Uncaught Promise > Invalid props for component 'https://github.com/messaging MessageFailedBox': unknown key 'record', 'chatterLocalId' is missing (should be a string)

**Comment by nicomacr** [comment]
@hvgollar the error is still present in the module as the last comment said.

**Comment by hvgollar** [comment]
> 



> @hvgollar the error is still present in the module as the last comment said.

Could help me in reproducing the issue.

**Comment by nicolascol** [comment]
> > 
> 
> > @hvgollar the error is still present in the module as the last comment said.
> 
> Could help me in reproducing the issue.

hi, the error is generated when entering the discuss app
@hvgollar

**Comment by rconjour** [comment]
@hvgollar can you please squash all your commits?

**Comment by hvgollar** [comment]
> @hvgollar can you please squash all your commits?

@rconjour Yes, its done

**Comment by nicomacr** [comment]
@hvgollar I faced this bug using the module `Promesa desconocida > "Directive t-foreach should always be used with a t-key!" (expression: t-foreach="messagefailed.failed_recipients" t-as="recipient")` Is happened when creating an activity.
Could you check the JS part?

**Review by chienandalu — COMMENTED** [review]
Hi @hvgollar 

Consider this v15 PRs that bring up some assorted fixes:

- https://github.com/OCA/social/pull/1053
- https://github.com/OCA/social/pull/1056
- https://github.com/OCA/social/pull/1057

**Review by chienandalu — CHANGES_REQUESTED** [review]
You should respect attribution of the changes you're including (cherry-picking or rebasing) not to include those in the migration commit.

**Comment by alan196** [comment]
I tested migration to V16 with a database with this module installed, It's failing to open views with failed messages.

It raises the following error in JS console.

````

Missing dependencies:     (6) ['mail.Manager.Notification', 'mail.model.AbstractMessage', 'mail.model.Message', 'mail.Discuss', 'mail.Manager', 'mail.model.Mailbox']0: "mail.Manager.Notification"1: "mail.model.AbstractMessage"2: "mail.model.Message"3: "mail.Discuss"4: "mail.Manager"5: "mail.model.Mailbox"length: 6[[Prototype]]: Array(0)
boot.js:347 Non loaded modules:       ['mail_tracking.FailedMessageDiscuss']0: "mail_tracking.FailedMessageDiscuss"length: 1[[Prototype]]: Array(0)
boot.js:355 Debug:                    {mail_tracking.FailedMessageDiscuss: {…}}mail_tracking.FailedMessageDiscuss: {dependencies: Array(8), dependents: Array(0), name: 'mail_tracking.FailedMessageDiscuss', missing: Array(6)}[[Prototype]]: Object
error_service.js:70 OwlError: Got duplicate key in t-foreach: false
    at MessagingClass.template (eval at compile (owl.js:5470:1), <anonymous>:232:51) (/web/static/lib/owl/owl.js:5470)
    at node.renderFn (owl.js:2633:1) (/web/static/lib/owl/owl.js:2633)
    at node.renderFn (owl.js:2642:1) (/web/static/lib/owl/owl.js:2642)
    at Fiber._render (owl.js:1621:1) (/web/static/lib/owl/owl.js:1621)
    at Fiber.render (owl.js:1613:1) (/web/static/lib/owl/owl.js:1613)
    at ComponentNode.initiateRender (owl.js:2352:1) (/web/static/lib/owl/owl.js:2352)
````

**Comment by pedrobaeza** [comment]
Superseded by #1091, as this one is not fully working.

**Pull request closed without merging**
