### PR TITLE
[12.0] mail_show_follower

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Comment by eLBati** [comment]
@ValentinVinagre thanks for this module.
What do you think of this proposal?

**Comment by ValentinVinagre** [comment]
Hi @eLBati ,
First of all, thanks for migrating the module to OCA. Overall it is good, but why do you remove the copyright and license? I think they should not be removed.
Please add yourself to the collaborators.

**Comment by eLBati** [comment]
@ValentinVinagre I removed copyright comments from python files except for `__manifest__.py `; I think they were redundant. I can bring them back if you prefer.

> Please add yourself to the collaborators

Done

**Review by HaraldPanten — APPROVED** [review]
It's working fine for us, as we've been using it internally since several months ago. I don't really know why runbot is failing.

**Comment by eLBati** [comment]
runbot has got deploy problems it seems:
```
Unable to find image 'oca-social:f0326a5_env_1_job_2' locally
docker: Error response from daemon: pull access denied for oca-social, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
cc @gurneyalex

**Review by rafaelbn — APPROVED** [review]
👍 +1

**Comment by ValentinVinagre** [comment]
@eLBati should tests be performed?

**Review by ValentinVinagre — APPROVED** [review]
👍🏻 LGTM

**Comment by HaraldPanten** [comment]
@rafaelbn I think this one can be merged

**Comment by HaraldPanten** [comment]
Any idea on how to solve runbot issue @gurneyalex @sbidoul ?

**Comment by rafaelbn** [comment]
Hello @moylop260 !!! What do you think here https://github.com/OCA/social/pull/711#issuecomment-843259491? Please...

**Comment by moylop260** [comment]
It looks an error in the previous step building the docker image:
 - Screen Shot 2021-06-07 at 10 01 48

I think something is wrong with the requirements
 - `cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).`

See the log here:
 - https://runbot.odoo-community.org/runbot/static/build/3486882-711-3b8033/logs/job_10_test_base.txt

**Comment by eLBati** [comment]
@ValentinVinagre what do you think
https://github.com/OCA/social/compare/3b8033402cfde9d56df5585d81dd5244e711fd5f..38cc46f918e6f4aa20959b4e357aa2b8f046b0aa
?

Did you already evalutae `notification_type`?

**Comment by eLBati** [comment]
Actually, this

https://github.com/OCA/social/pull/711/commits/0249453ac39ef5402c34d7c49162b7fe407bbd6c#diff-b44d3d8a58eb40149e86dfa92e460ba5597bdab00d92d09f71c1d56c76a6444fR60-R67

**Comment by ValentinVinagre** [comment]
Hi @eLBati ,
I'm quite busy these days, when I have a hole I look at it :D

**Comment by ValentinVinagre** [comment]
@dreispt please abort because the last imp hasn't been reviewed. Thanks

**Pull request merged**
