### PR TITLE
[15.0][IMP] mail_activity_board: Direct access to related model instance (forward port)

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Forward port of https://github.com/OCA/social/pull/885.

### CODE REVIEW

**Review by flotho — CHANGES_REQUESTED** [review]
Hi, I've tested on runboat,
any chance to improve the display so that we can see teh hyperlingk :
image

**Review by atchuthan — APPROVED** [review]

**Comment by rafaelbn** [comment]
@MiquelRForgeFlow please check https://github.com/OCA/social/pull/887#pullrequestreview-933868471

**Comment by MiquelRForgeFlow** [comment]
@flotho @rafaelbn done

**Review by rafaelbn — APPROVED** [review]
👍

**Review by flotho — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
Can we merge this?

**Comment by atchuthan** [comment]
@OCA/social-maintainers PR is ready for merging with 3 votes

**Review by etobella — APPROVED** [review]

**Pull request merged**
