### PR TITLE
[13.0][MIG] mail_debrand: Migration to 13.0 

### PR DESCRIPTION
**Pull request by ValentinVinagre**
Standard migration.

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
Tested in local environment and it works fine. Functional review 👍

**Comment by pedrobaeza** [comment]
Is this affected by #441?

**Comment by ValentinVinagre** [comment]
Hi @pedrobaeza ,
I didn't see this issue, I will test it and I will tell you something.

**Comment by ValentinVinagre** [comment]
Hi @pedrobaeza ,
I tested different use cases, and all seems to work fine:

1.- I created 4 contact with different languages: English (US), Czech / Čeština, Spanish / Español, Basque / Euskara.
2.- I'm changing the active language for the user that is sending the emails, and I'm repeating steps 2.1, 2.2, and 2.3:
    2.1.- I created 1 sale for every contact, and all correct.
    2.2.- I created 1 invoice for every contact, and all correct.
    2.3.- I created 1 purchase for every contact, and all correct.

But if you want I can use the solution proposed in https://github.com/OCA/social/pull/507 that I think will solve the https://github.com/OCA/social/issues/441 .

**Comment by ValentinVinagre** [comment]
Hi @chienandalu ,
The issue with translations is only in the v. 11.0-12.0? Because I tried and I don't found the problem in v.13

Thanks,

**Comment by chienandalu** [comment]
Well from V12 the notification template is a qweb record so there should be no issue, I think

**Comment by ValentinVinagre** [comment]
Thanks @chienandalu , so if the problem doesn't exist in v.13 I don't see the need to transfer the fix @pedrobaeza .

**Comment by pedrobaeza** [comment]
OK, perfect

**Review by tarteo — APPROVED** [review]
Thanks!

**Pull request merged**
