### PR TITLE
[FIX] mail_quoted_reply: fix duplicating reply icon

### PR DESCRIPTION
**Pull request by em230418**
Fixes https://github.com/OCA/social/issues/1239

### CODE REVIEW

**Review by jonasbuchholz — APPROVED** [review]

**Comment by jonasbuchholz** [comment]
@etobella could you review this fix?

**Comment by etobella** [comment]
It works better now, but I was able to reproduce the error on runboat for the PR

image

**Comment by etobella** [comment]
image


How to reproduce the error:

- Mark a message
- Click on the recipent
- Go Back to the original thread: Now you have two elements

**Comment by jonasbuchholz** [comment]
You are correct, leaving the thread and coming back to it adds additional icons. I tried a different fix in #1185 that doesn't seem to have that issue, but it has a little more overhead because it checks the action list every time. @em230418 what do you think?

**Comment by etobella** [comment]
I prefer the other option, as the bug is shouldn't be there :wink:

**Pull request closed without merging**
