### PR TITLE
[8.0][website_mail_snippet_tr_edit] Edit <tr> in your mails.

### PR DESCRIPTION
**Pull request by yajo**
With this module, you can now duplicate or delete <tr> elements in your table-based templates or snippets for emails.

@rafaelbn

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can't you insert tables at your own?

Maybe the name should be `table` instead of `tr` to be more descriptive.

What about an icon of a table :wink:?

**Comment by yajo** [comment]
> Can't you insert tables at your own?

I tried but some weird behavior inside the Odoo drag & drop engine does not allow that. It's in the known issues.

> Maybe the name should be table instead of tr to be more descriptive.
> What about an icon of a table :wink:?

Thanks, fixed.

**Comment by pedrobaeza** [comment]
Oh, what a pity! There's no possibility then to insert tables in an empty template?

**Comment by dgzurita** [comment]
Tested in runbot. Perfect! :+1:

**Comment by yajo** [comment]
@pedrobaeza at least not to move them around

**Comment by rafaelbn** [comment]
Thanks! snippets become useful! :+1: :smile:

**Comment by pedrobaeza** [comment]
:+1: Thanks for the cool icon!

**Comment by pedrobaeza** [comment]
One last question. Can't this be done for all the website builder instead only the mail part? Is not the same code? Or they are different snippets?

**Comment by rafaelbn** [comment]
Let's @Yajo answer but as I talked with him, they are different snippet.

**Comment by yajo** [comment]
They are different.

**Pull request merged**
