### PR TITLE
[IMP] mail_activity_team: Forwarding commits from 13.0 to 15.0

### PR DESCRIPTION
**Pull request by olgamarcocb**
Includes (besides small changes):

- #912 
- #919 

@etobella 

There are warnings associated with MailActivity._onchange_team_id and MailActivity._onchange_user_id, we think about using https://github.com/odoo/odoo/pull/41918 but it would be a problem if a BBDD with many users is used. What do you think?

### CODE REVIEW

**Comment by etobella** [comment]
Why not using web_domain_field?

@LoisRForgeFlow WDYT?

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
Maybe wait first https://github.com/OCA/social/pull/920 gets merged, and then cherry-pick from there.

**Comment by MiquelRForgeFlow** [comment]
https://github.com/OCA/social/pull/920 was merged, please, restore the commits using the ones from that PR.

**Comment by MiquelRForgeFlow** [comment]
@etobella who will retake this?

**Comment by etobella** [comment]
Myself :wink:

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
