### PR TITLE
[PORT] porting js code to comply with OWL

### PR DESCRIPTION
**Pull request by houssine78**
As the JS code of the chatter is made under the OWL framework the mail_tracking isn't work on v14
On behalf of @asmaelferkhsi-ra

### CODE REVIEW

**Review by alan196 — APPROVED** [review]
Tested in my production database migrated from V12 👍  Works perfectly. But it has pre-commit issues

**Comment by visiniaga** [comment]
Greatt, it worked, tested in odoo 14.0+e-20211018

**Review by ao-landoo — APPROVED** [review]
Works great, thanks for the fix!

**Comment by moylop260** [comment]
@houssine78 

Thank you!

Will you check the red CI, right?

It is raising the following error:

/home/travis/build/OCA/social/setup/mail_tracking/odoo/addons/mail_tracking/tests/test_mail_tracking.py", line 302, in test_failed_message
    self.assertEqual(values["author"][0], -1)
    TypeError: 'NoneType' object is not subscriptable

**Comment by moylop260** [comment]
@houssine78 

Also

Could you run `pre-commit run --all` in order to autofix lints, please?

**Comment by houssine78** [comment]
Hi, 

Thanks to all of you for your reviews and comments. We will handle pre-commit issue soon.

Regards,
Houssine

**Comment by houssine78** [comment]
Hi @moylop260 could you approve the workflow to run ? my colleague is a first time contributor so workflow doesn't run automatically.

thanks !!

**Comment by houssine78** [comment]
Hi

pre-commit style failing on a black issue and I have no idea on how to fix it. Any help is welcome

here is the error that we get
image

**Comment by houssine78** [comment]
Hi @pedrobaeza,

Any clue on how to solve this ? 

Thank you !
Houssine

**Comment by pedrobaeza** [comment]
Very weird error. Can you rebase over latest main branch to see if latest pushes on the template fix it?

**Comment by houssine78** [comment]
Thanks @pedrobaeza ! I'll try that !

**Comment by houssine78** [comment]
@pedrobaeza it still fail with the same error after rebase.

**Comment by pedrobaeza** [comment]
@Yajo can you please check if you see something incorrect in the pre-commit config?

**Comment by yajo** [comment]
It's the 2nd time I see that error today on our CIs. It's quite weird, anybody knows if anything has changed in the CI these days?

**Comment by houssine78** [comment]
@sbidoul @gurneyalex any though on this error ? Thanks !

**Comment by pedrobaeza** [comment]
We have discovered the problem, and it's general:

https://github.com/OCA/oca-addons-repo-template/pull/89

**Comment by houssine78** [comment]
@pedrobaeza pre-commit is green now thanks !!

can we merge the PR ?

**Pull request merged**
