### PR TITLE
[FIX] Call to generate_email can be done with a list of ids or only o…

### PR DESCRIPTION
**Pull request by lmignon**
…ne id

fix oca/social#64

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by lmignon** [comment]
ping @lasley

**Comment by lasley** [comment]
Good call 👍

**Comment by lmignon** [comment]
@hbrunn This one is for you :smirk:

**Comment by hbrunn** [comment]
:+1:

**Comment by lmignon** [comment]
thank you @hbrunn and others revierwers!

**Pull request merged**
