### PR TITLE
port mail_check_mailbox_size to 12.0

### PR DESCRIPTION
**Pull request by lepistone**
I tested this manually on two IMAP accounts of different providers, one of which with more than 200MB of emails.

### CODE REVIEW

**Comment by eLBati** [comment]
@lepistone please fix travis `mail_check_mailbox_size/models/fetchmail.py:81:80: E501 line too long (81 > 79 characters)` and squash commits in 1 migration commit.
Then OK for me
Thanks!

**Comment by lepistone** [comment]
@eLBati better later than never, I fixed lint, squashed into a single commit with a message covering all the changes and rebased. I think we can merge!

**Review by eLBati — CHANGES_REQUESTED** [review]
@lepistone thanks!

Could you isolate the migration commit, following https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0#technical-method-to-migrate-a-module-from-110-to-120-branch ?

**Comment by lepistone** [comment]
@eLBati done!

**Review by eLBati — APPROVED** [review]
Tested

**Pull request merged**
