### PR TITLE
[15.0][MIG] mail_partner_opt_out

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
@ForgeFlow 
Stardand Migration

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
@OCA-git-bot do not close this

**Review by mariadforgeflow — APPROVED** [review]
Functional test. LGTM!

**Review by JaumeBforgeFlow — APPROVED** [review]
LGTM!

**Review by GuillemCForgeFlow — APPROVED** [review]
Functional review! LGTM 👍🏽

**Review by AaronHForgeFlow — APPROVED** [review]
Code review

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by etobella — APPROVED** [review]
/ocabot migration mail_partner_opt_out

**Pull request merged**
