### PR TITLE
[16.0][MIG] base_search_mail_content

### PR DESCRIPTION
**Pull request by Highcooley**

### CODE REVIEW

**Review by luis-ron — APPROVED** [review]
Functional review, LGTM

**Review by Shide — CHANGES_REQUESTED** [review]
I'm not able to search on `message_content` field (the one that adds this module) on any view.

The option to search should appear on the bottom of the search filters.

mc

Please test the migrated module by yourself before making it ready to review or mark it like draft.

**Comment by yajo** [comment]
https://github.com/OCA/social/pull/1164 works, this one doesn't. Let's continue there. Thanks everyone!

**Pull request closed without merging**
