### PR TITLE
[14.0] [MIG] mail activity done

### PR DESCRIPTION
**Pull request by chrisandrewmann**

### CODE REVIEW

**Comment by rafaelbn** [comment]
@chrisandrewmann do you want to reopen please? I can take care of this one 😄

**Comment by chrisandrewmann** [comment]
@rafaelbn Thanks for the message. However I closed my own PR when I realised someone else had already done it before!

**Comment by rafaelbn** [comment]
Yes! Thank you! I'm going to update the issue of migration! 😄 

https://github.com/OCA/social/pull/758

**Pull request closed without merging**
