### PR TITLE
[15.0][IMP] mail_activity_board: Add group so that the activity dashboard is only visible if the user has the permission.

### PR DESCRIPTION
**Pull request by victoralmau**
Add group so that the activity dashboard is only visible if the user has the permission.

Please @pedrobaeza and @CarlosRoca13 can you review it?

@Tecnativa TT43037

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Is this still draft?

**Comment by victoralmau** [comment]
This is ready for review.

**Comment by victoralmau** [comment]
Can you review it again?

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge minor

**Pull request merged**
