### PR TITLE
12.0 mig mail footer notified partner

### PR DESCRIPTION
**Pull request by Tonow-c2c**
Related to #289 

image

### CODE REVIEW

**Comment by guilhom34** [comment]
@pedrobaeza can you validate this PR?

**Comment by pedrobaeza** [comment]
Sorry, I don't know this module.

**Comment by guilhom34** [comment]
Thank you for your answear, what can I do to help validating this ?

**Comment by pedrobaeza** [comment]
You can review it, functionally or technically.

https://odoo-community.org/page/review

**Comment by guilhom34** [comment]
Thank you so much :)

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by guilhom34 — APPROVED** [review]
everything is fine

**Review by len-foss — APPROVED** [review]
During my tests I've made a small improvement in commit https://github.com/acsone/social/commit/79db695f8f72f2c28de67fb66babedc686a51430 that only adds the footer if there are more than one recipients.

Anyway everything works fine in current PR.

**Comment by flotho** [comment]
Hi @hbrunn , @antespi ,

This PR has been validated by 3 personnes. could it be merged ?

Regards

**Pull request merged**
