### PR TITLE
[18.0][MIG] mail_layout_preview: Migration to 18.0

### PR DESCRIPTION
**Pull request by Kimkhoi3010**

### CODE REVIEW

**Comment by sebalix** [comment]
PR based on v17 migration PR:
- https://github.com/OCA/social/pull/1371

/ocabot migration mail_layout_preview

**Review by TDu — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
This should go to OCA/mail instead.

**Comment by Kimkhoi3010** [comment]
@pedrobaeza, I updated by your comments, and created a new PR [OCA#7](https://github.com/OCA/mail/pull/7) to OCA/mail.
(This PR was closed after I create new PR to OCA/mail)

**Comment by Kimkhoi3010** [comment]
@pedrobaeza, I updated by your comments, and created a new PR https://github.com/OCA/mail/pull/7 to OCA/mail.
(This PR was closed after I create new PR to OCA/mail)

**Pull request closed without merging**
