### PR TITLE
[16.0][MIG] outgoing_email_by_model: Migration from 15.0 to 16.0

### PR DESCRIPTION
**Pull request by emiliesoutiras**

### CODE REVIEW

**Review by hbrunn — CHANGES_REQUESTED** [review]
please follow the [migration guide](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0), most notably keeping commit history

**Review by hbrunn — APPROVED** [review]
tests are fixed in https://github.com/OCA/social/pull/1519

**Comment by emiliesoutiras** [comment]
@Kev-Roche, @metaminux, to review

**Review by metaminux — APPROVED** [review]
LGTM

**Pull request merged**
