### PR TITLE
[ADD] New module mail_discuss_security to hide 'Discuss' Application by default

### PR DESCRIPTION
**Pull request by legalsylvain**
trivial module.

### Description

In odoo, by default, all user can see messages ("Discuss" menu entry).
This feature is not interesting in some instances.

This module so creates a new group 'See Discuss Menu' to display this entry menu
and users are not member of this group by default.

menu_list

Also in the systray, the message icon is removed:

systray

### CODE REVIEW

**Review by hparfr — APPROVED** [review]

**Review by quentinDupont — APPROVED** [review]
Tested with success on runboat and code review :heavy_check_mark:

**Review by hbrunn — APPROVED** [review]

**Comment by legalsylvain** [comment]
Hi all. I have a problem with the current implementation of this module.

UPDATE : removing the line ``-    dependencies: ["messaging"], ``looks to fix the problem.

Step to reproduce : 
- install mail_discuss_group
- All is working perfectly, element are hidden (and shown if we are member of the new group)
- Install point_of_sale module and launch point of sale.
- a blocking javascript error occures

<details>
<summary>Click to see Javascript error</summary>
<code>
Unncaught (in promise) Error: Some services could not be started: mail_discuss_group_systray_service. Missing dependencies: messaging
    _startServices env.js:156
    startServices env.js:85
    startWebClient start.js:33
    startPosApp main.js:33
    <anonymous> main.js:36
    def boot.js:128
    processJob boot.js:126
    processJobs boot.js:197
    def boot.js:138
    promise callback*processJobs/processJob/def< boot.js:135
    processJob boot.js:126
    processJobs boot.js:197
    def boot.js:138
    promise callback*processJobs/processJob/def< boot.js:135
    processJob boot.js:126
    processJobs boot.js:197
    define boot.js:254
    <anonymous> point_of_sale.assets_backend_prod_only.js:236
[env.js:156](http://localhost:8016/web/static/src/env.js)
    startWebClient start.js:33
    AsyncFunctionThrow self-hosted:811
    (Asynchrone : async)
    startPosApp main.js:33
    <anonyme> main.js:36
    def boot.js:128
    processJob boot.js:126
    processJobs boot.js:197
    def boot.js:138
    (Asynchrone : promise callback)
    def boot.js:135
    processJob boot.js:126
    processJobs boot.js:197
    def boot.js:138
    (Asynchrone : promise callback)
    def boot.js:135
    processJob boot.js:126
    processJobs boot.js:197
    define boot.js:254
    <anonyme> point_of_sale.assets_backend_prod_only.js:236

Error: Some services could not be started: mail_discuss_group_systray_service. Missing dependencies: messaging
    _startServices@http://localhost:8016/web/assets/debug/point_of_sale.pos_assets_backend.js:64540:15 (/web/static/src/env.js:156)
    async*startServices@http://localhost:8016/web/assets/debug/point_of_sale.pos_assets_backend.js:64469:11 (/web/static/src/env.js:85)
    async*startWebClient@http://localhost:8016/web/assets/debug/point_of_sale.assets_backend_prod_only.js:183:11 (/web/static/src/start.js:33)
    startPosApp@http://localhost:8016/web/assets/debug/point_of_sale.assets_backend_prod_only.js:135:19 (/point_of_sale/static/src/entry/main.js:33)
    @http://localhost:8016/web/assets/debug/point_of_sale.assets_backend_prod_only.js:138:1 (/point_of_sale/static/src/entry/main.js:36)
    processJobs/processJob/def<@http://localhost:8016/web/assets/debug/web.assets_common.js:162:47 (/web/static/src/boot.js:128)
    processJob@http://localhost:8016/web/assets/debug/web.assets_common.js:160:27 (/web/static/src/boot.js:126)
    processJobs@http://localhost:8016/web/assets/debug/web.assets_common.js:231:27 (/web/static/src/boot.js:197)
    processJobs/processJob/def</<@http://localhost:8016/web/assets/debug/web.assets_common.js:172:48 (/web/static/src/boot.js:138)
    promise callback*processJobs/processJob/def<@http://localhost:8016/web/assets/debug/web.assets_common.js:169:30 (/web/static/src/boot.js:135)
    processJob@http://localhost:8016/web/assets/debug/web.assets_common.js:160:27 (/web/static/src/boot.js:126)
    processJobs@http://localhost:8016/web/assets/debug/web.assets_common.js:231:27 (/web/static/src/boot.js:197)
    processJobs/processJob/def</<@http://localhost:8016/web/assets/debug/web.assets_common.js:172:48 (/web/static/src/boot.js:138)
    promise callback*processJobs/processJob/def<@http://localhost:8016/web/assets/debug/web.assets_common.js:169:30 (/web/static/src/boot.js:135)
    processJob@http://localhost:8016/web/assets/debug/web.assets_common.js:160:27 (/web/static/src/boot.js:126)
    processJobs@http://localhost:8016/web/assets/debug/web.assets_common.js:231:27 (/web/static/src/boot.js:197)
    odoo.define@http://localhost:8016/web/assets/debug/web.assets_common.js:288:24 (/web/static/src/boot.js:254)
    @http://localhost:8016/web/assets/debug/point_of_sale.assets_backend_prod_only.js:236:6 (http://localhost:8016/web/assets/debug/point_of_sale.assets_backend_prod_only.js:236) [error_service.js:73](http://localhost:8016/web/static/src/core/errors/error_service.js)
    handleError error_service.js:73
    start error_service.js:130
    start error_service.js:119
    start env.js:111
    _startServices env.js:142
    startServices env.js:85
    startWebClient start.js:33
    startPosApp main.js:33
    <anonyme> main.js:36
    def boot.js:128
    processJob boot.js:126
    processJobs boot.js:197
    def boot.js:138
    (Asynchrone : promise callback)
    def boot.js:135
    processJob boot.js:126
    processJobs boot.js:197
    def boot.js:138
    (Asynchrone : promise callback)
    def boot.js:135
    processJob boot.js:126
    processJobs boot.js:197
    define boot.js:254
    <anonyme> point_of_sale.assets_backend_prod_only.js:236

Uncaught (in promise) Error: Some services could not be started: mail_discuss_group_systray_service. Missing dependencies: messaging
    _startServices env.js:156
    startServices env.js:85
    startWebClient start.js:33
    startPosApp main.js:33
    <anonymous> main.js:36
    def boot.js:128
    processJob boot.js:126
    processJobs boot.js:197
    def boot.js:138
    promise callback*processJobs/processJob/def< boot.js:135
    processJob boot.js:126
    processJobs boot.js:197
    def boot.js:138
    promise callback*processJobs/processJob/def< boot.js:135
    processJob boot.js:126
    processJobs boot.js:197
    define boot.js:254
    <anonymous> point_of_sale.assets_backend_prod_only.js:236
[env.js:156](http://localhost:8016/web/static/src/env.js)
    start error_service.js:127
    AsyncFunctionThrow self-hosted:811
    (Asynchrone : async)
    start error_service.js:119
    start env.js:111
    _startServices env.js:142
    startServices env.js:85
    InterpretGeneratorResume self-hosted:1420
    AsyncFunctionNext self-hosted:807
    (Asynchrone : async)
    startWebClient start.js:33
    startPosApp main.js:33
    <anonyme> main.js:36
    def boot.js:128
    processJob boot.js:126
    processJobs boot.js:197
    def boot.js:138
    (Asynchrone : promise callback)
    def boot.js:135
    processJob boot.js:126
    processJobs boot.js:197
    def boot.js:138
    (Asynchrone : promise callback)
    def boot.js:135
    processJob boot.js:126
    processJobs boot.js:197
    define boot.js:254
    <anonyme> point_of_sale.assets_backend_prod_only.js:236
</code>
</details>

I'm pretty lost. I introduced the asset in web.assets_backend bundle. So, If I understand correctly, this bundle is not loaded in the point of sale, so error should not occures.
Ref : doc : https://www.odoo.com/documentation/17.0/fr/developer/reference/frontend/assets.html#bundles

- the systray_service.js file looks like [the original one](https://github.com/odoo/odoo/blob/16.0/addons/mail/static/src/services/systray_service.js). The original file is introduced in the web.assets_backend bundle in the  ``mail`` [manifest file](https://github.com/odoo/odoo/blob/16.0/addons/mail/__manifest__.py#L191).  

@OCA/web-maintainers : Any help welcome ! 

Thanks !

**Comment by pedrobaeza** [comment]
Existing a model called `mail.group`, the module name is misleading. I think it should be called `mail_discuss_security`.

**Comment by legalsylvain** [comment]
> Existing a model called mail.group, the module name is misleading. I think it should be called mail_discuss_security.

agree ! ``_security`` is indeed a common suffix for such feature.

**Comment by tarteo** [comment]
@legalsylvain where is the messaging service defined? Perhaps you're missing a dependency in you manifest

**Edit:**
Found it (it's in mail)
Do you still get the error if you add the line `import { messagingService } from '@mail/services/messaging_service';` to your file? I know it's stupid but I want to rule out if it's a load order issue (I doubt it but still)

**Comment by legalsylvain** [comment]
hi @tarteo. Thanks for your review. In fact I updated my comment, with ``UPDATE : removing the line -    dependencies: ["messaging"], looks to fix the problem.`` because I found the problem. I just remove the dependency to "messaging", and it work.
sorry if you lost time to investigate.

At this step, this PR is ready to review and to be merged.

**Review by tarteo — APPROVED** [review]
@legalsylvain No problem, just tested it and it works!

**Comment by legalsylvain** [comment]
4 approvals. 
Let'go ! 

/ocabot merge nobump

**Pull request merged**
