### PR TITLE
[11.0][IMP] mail_activity_board: filter activities by user read permissions

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
As commented in https://github.com/OCA/social/issues/335.

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Error accessing with demo user:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/OCB-11.0/addons/web/controllers/main.py", line 876, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/home/odoo/OCB-11.0/addons/web/controllers/main.py", line 898, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/.repo_requirements/odoo/odoo/models.py", line 4222, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/.repo_requirements/odoo/odoo/models.py", line 1480, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/odoo/build/OCA/social/mail_activity_board/models/mail_activity.py", line 92, in _search
    WHERE a.id = ANY (%%(ids)s)""" % self._table, dict(ids=ids))
  File "/.repo_requirements/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: syntax error at or near "a"
LINE 4:             LEFT JOIN ir_model im ON im.id a.res_model_id
                                                   ^
```

**Comment by MiquelRForgeFlow** [comment]
@lreficent please update review

**Review by LoisRForgeFlow — APPROVED** [review]
Works fine :+1:

**Review by LoisRForgeFlow — COMMENTED** [review]
Some small test would be great

**Review by jarroyomorales — APPROVED** [review]
LGTM :+1: Functional test working as expected
Bump version, and it would be great to add a small test.

**Comment by MiquelRForgeFlow** [comment]
Hello everybody, the tests have been added! update reviews please!

@hbrunn please, remove "needs tests" tag.

**Comment by LoisRForgeFlow** [comment]
Thank you, LGTM :+1:

**Review by emagdalenaC2i — APPROVED** [review]
Code review

**Pull request merged**
