### PR TITLE
[FIX][website_mass_mailing_name] Show disabled name.

### PR DESCRIPTION
**Pull request by yajo**
When the snippet appears as disabled, do not hide the name field.

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by rafaelbn** [comment]
Thanks :+1:

**Comment by antespi** [comment]
Running a simple test in runbot, this fix doesn't seem to work or I miss something. 

Use case:
1. I've created a newsletter subscripcion in home page and save
2. I've subscribed throught it and reload page
3. Mi name doesn't appears, but email and Thanks text yes.

**Comment by yajo** [comment]
1. Go to other runbot.
2. Log in as demo user.
3. Create a subscription snippet with name and email.
4. Subscribe.
5. Reload page.

Name field disappears:
captura de pantalla de 2016-09-09 13-02-02

**Comment by antespi** [comment]
Yes, in this runbot, name disappears too. Same behavior.

**Comment by gurneyalex** [comment]
@antespi @Yajo could it be an interaction with another installed module on runbot?

**Comment by rafaelbn** [comment]
Hi, I tested again un runbot in a base database + this module



It's OK, isn't it?

**Comment by antespi** [comment]
@rafaelbn You have to log in and subscribe. After that reload the page

**Comment by rafaelbn** [comment]
:open_mouth: you are absolutelly right. @Yajo please check again
- http://3153739-83-cfc337.runbot1.odoo-community.org/
- Base database
- login paco@paco.es / paco

**Comment by rafaelbn** [comment]
Hi @Yajo could you please review here?

**Comment by yajo** [comment]
sorry, the problem was that the compiled css file came from an older version. I just recompiled the Sass and it should be fixed now.

**Pull request merged**
