### PR TITLE
FIX mail_notify_bounce: TypeError: decoding Unicode is not supported

### PR DESCRIPTION
**Pull request by eLBati**
as message_dict['body'] is unicode yet

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by tafaRU — APPROVED** [review]

**Comment by eLBati** [comment]
oops merged too fast: https://travis-ci.org/OCA/social/builds/356821665
I'm working on it

**Comment by hbrunn** [comment]
@eLBati I merged this too soon, can you have another look please? This breaks tests: https://travis-ci.org/OCA/social/jobs/356821668#L1708

**Comment by hbrunn** [comment]
ah, now I see the message ;-) thanks. Why not just use https://github.com/OCA/OCB/blob/11.0/odoo/loglevels.py#L43 ? and why didn't I ask this during review?

**Comment by eLBati** [comment]
Here it is https://github.com/OCA/social/pull/248

**Pull request merged**
