### PR TITLE
[16.0][MIG] mail_notification_custom_subject

### PR DESCRIPTION
**Pull request by edlopen**
Standard migration to v16.

@moduon MT-7401

@Shide @yajo @EmilioPascual @rafaelbn please review, if you can.

### CODE REVIEW

**Review by yajo — APPROVED** [review]
Code review

**Review by EmilioPascual — APPROVED** [review]
Review code

**Review by pedrobaeza — COMMENTED** [review]
Please split the pre-commit changes from the migration itself as stated in the migration guide

/ocabot migration mail_notification_custom_subject

**Comment by edlopen** [comment]
@pedrobaeza done! Can you revise again please? Thank you!

**Comment by pedrobaeza** [comment]
OK, more or less, although the README changes should happen in the migration one, but let's not block more:

/ocabot merge nobump

**Pull request merged**
