### PR TITLE
[FIX] re.search will return None when nothing found. So we have to check for this

### PR DESCRIPTION
**Pull request by wpichler**

### CODE REVIEW

**Review by yajo — APPROVED** [review]

**Comment by yajo** [comment]
I "fast" track it as it is pretty obvious.

**Comment by pedrobaeza** [comment]
Let's call it correctly :wink: 

/ocabot merge patch

**Comment by pedrobaeza** [comment]
Is this needed for v13 as well?

**Comment by wpichler** [comment]
> Is this needed for v13 as well?

just looked at v13 - it is also needed there...

**Comment by pedrobaeza** [comment]
Cherry-pick to v13 in 05905e50c383e0ebe520e4f3a941853811d47495

**Pull request merged**
