### PR TITLE
[15.0][MIG]mail_debrand: migration from 14.0 to 15.0

### PR DESCRIPTION
**Pull request by AlvaroTForgeFlow**
@ForgeFlow

### CODE REVIEW

**Review by JoanMForgeFlow — APPROVED** [review]
LGTM! functional review OK!

**Comment by Bart-dh** [comment]
Ok!

**Review by Bart-dh — APPROVED** [review]
Ok!

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! :+1:

**Comment by rafaelbn** [comment]
https://github.com/OCA/social/issues/839

**Pull request merged**
