### PR TITLE
[MIG] mail_improved_tracking_value: Migration to 14.0

### PR DESCRIPTION
**Pull request by Zar21**
Standard migration to 14.0

### CODE REVIEW

**Comment by pafnow** [comment]
Hi, thanks for the migration.
I have an error when opening the improved tracking view, it seems that _compute_formatted_value is not properly handling Many2one fields.
To fix it, I changed 
```
    def _compute_formatted_value(self):
        """ Sets the value formatted field used in the view """
        for record in self:
            if record.field_type in ("many2many", "one2many", "char"):
```
to
```
    def _compute_formatted_value(self):
        """ Sets the value formatted field used in the view """
        for record in self:
            if record.field_type in ("many2many", "one2many", "char", "many2one"):
```

And all is working now.

**Comment by mbcosta** [comment]
Hi @pafnow I tested the case that not working without this module, tracking Many2many fields:

image

image

And tested the Many2one case, that works with or without this module:

image

image

image

Can you put some image or the error message of the problem that you are trying to solve?

Thanks @Zar21 for module migration, I just will wait to see the anwser of the possible problem reported before approve, but for me it's seems everything right.

**Comment by houssine78** [comment]
Hi @Zar21 any chance that you'll find some time to take the comments into account ? It will be well appreciated ! Thanks for the migration PR !

**Comment by ferran-S73** [comment]
Hey @pafnow @mbcosta do you consider there's still something to do here or can this be merged?

**Review by mbcosta — APPROVED** [review]
Hi @ferran-S73 for me the PR can be merged, for now I don't see the problem "an error when opening the improved tracking view" reported by @pafnow , I appreciated if someone can explain or, if necessary, open a new PR with Fix. For now I approve this PR, it's working as proposed.

**Review by ioans73 — APPROVED** [review]
LGTM

**Comment by ferran-S73** [comment]
@OCA/social-maintainers could someone review this PR please?

**Review by ferran-S73 — APPROVED** [review]

**Review by simahawk — APPROVED** [review]

**Pull request merged**
