### PR TITLE
[14.0][MIG] mail_tracking: Migration to 14.0

### PR DESCRIPTION
**Pull request by AreebSiddiqiIR**

### CODE REVIEW

**Comment by moylop260** [comment]
@AreebSiddiqiIR 

Could you check the [CI error](https://travis-ci.com/github/OCA/social/jobs/502747004#L921) running the unittest, please?

```txt
2021-05-03 23:27:45,735 5852 INFO openerp_test odoo.addons.mail_tracking.tests.test_mail_tracking: Starting TestMailTracking.test_bounce_new_partner ...
2021-05-03 23:27:45,796 5852 ERROR openerp_test odoo.addons.mail.models.mail_mail: failed sending mail (id: 1) due to 'tuple' object has no attribute 'startswith'
Traceback (most recent call last):
File "/home/travis/odoo-14.0/addons/mail/models/mail_mail.py", line 369, in _send
headers=headers)
File "/home/travis/build/OCA/social/setup/mail_tracking/odoo/addons/mail_tracking/models/ir_mail_server.py", line 64, in build_email
subtype_alternative=subtype_alternative,
File "/home/travis/odoo-14.0/odoo/addons/base/models/ir_mail_server.py", line 318, in build_email
msg[pycompat.to_text(ustr(key))] = value
File "/opt/python/3.6.7/lib/python3.6/email/message.py", line 409, in __setitem__
self._headers.append(self.policy.header_store_parse(name, val))
File "/opt/python/3.6.7/lib/python3.6/email/policy.py", line 147, in header_store_parse
return (name, self.header_factory(name, value))
File "/opt/python/3.6.7/lib/python3.6/email/headerregistry.py", line 589, in __call__
return self[name](name, value)
File "/opt/python/3.6.7/lib/python3.6/email/headerregistry.py", line 197, in __new__
cls.parse(value, kwds)
File "/opt/python/3.6.7/lib/python3.6/email/headerregistry.py", line 272, in parse
kwds['parse_tree'] = cls.value_parser(value)
File "/opt/python/3.6.7/lib/python3.6/email/_header_value_parser.py", line 1084, in get_unstructured
if value.startswith('=?'):
AttributeError: 'tuple' object has no attribute 'startswith'
```

**Comment by moylop260** [comment]
Could you comment in the [migration 14.0 issue](https://github.com/OCA/social/issues/620) in order to notify other contributors that you are working in this migration, please?

**Comment by moylop260** [comment]
@AreebSiddiqiIR 


Could you use a `pdb`, please?
And debug what value is receiving now and what value was received in last version, please?

**Comment by AreebSiddiqiIR** [comment]
The commit: https://github.com/odoo/odoo/commit/a4e1b7c44e77ad2abf1be05ccffacde65a051822 changed function message_format https://github.com/odoo/odoo/blob/d1d523e4836195da6b081253f258a2653f35ded2/addons/mail/models/mail_message.py#L1072 so that it no longer has "partner_trackings" in the dictionary, which causes https://github.com/OCA/social/blob/0741c91453d48c48e3d3ac5619753b1afe4fe8f7/mail_tracking/tests/test_mail_tracking.py#L212 to fail.

Since it has been removed, we need a replacement.

@moylop260

**Comment by AreebSiddiqiIR** [comment]
> The commit: [odoo/odoo@a4e1b7c](https://github.com/odoo/odoo/commit/a4e1b7c44e77ad2abf1be05ccffacde65a051822) changed function message_format https://github.com/odoo/odoo/blob/d1d523e4836195da6b081253f258a2653f35ded2/addons/mail/models/mail_message.py#L1072 so that it no longer has "partner_trackings" in the dictionary, which causes
> 
> https://github.com/OCA/social/blob/0741c91453d48c48e3d3ac5619753b1afe4fe8f7/mail_tracking/tests/test_mail_tracking.py#L212
> 
> to fail.
> Since it has been removed, we need a replacement.
> 
> @moylop260


@pedrobaeza The test in this module uses key:  "partner_trackings", which is no longer being used. Do you have an alternative way to do this test? Thank you!

**Comment by pedrobaeza** [comment]
I haven't checked anything yet about this module and its migration, sorry.

**Comment by angelJuaGar** [comment]
I will continue with the migration of this module to correct the unitest in this new pr
https://github.com/OCA/social/pull/731

**Pull request closed without merging**
