### PR TITLE
[10.0][MIG] mass_mailing_security_group

### PR DESCRIPTION
**Pull request by luismontalba**
Mass mailing security group
-----------------------------------
This module adds these security features:
* ACL for allowing marketing user group to remove mass.mailing objects
* Security rule to allow marketing user to delete only his unsent
  mail.mass_mailing objects
* Security rule to allow marketing manager to delete all unsent
  mail.mass_mailing objects

For sent mail.mass_mailing objects, only a user in Administration / Settings
group could remove them, like standard Odoo defines.

cc @Tecnativa

### CODE REVIEW

**Comment by yajo** [comment]
Please check the bots.

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
I think this module is not needed:
* In this version, there's a group mass mailing user that allows to unlink mass mailings (https://github.com/odoo/odoo/blob/74918dfa374e6d0468eccd881cb418d923da72ca/addons/mass_mailing/security/ir.model.access.csv#L8),
* There are no restriction for unlinking records. Maybe we want this restriction...
* ondelete='cascade' is already set on the TransientModel (https://github.com/odoo/odoo/blob/74918dfa374e6d0468eccd881cb418d923da72ca/addons/mass_mailing/wizard/test_mailing.py#L13)

What do you think?

**Comment by yajo** [comment]
> There are no restriction for unlinking records. Maybe we want this restriction...

I think this was added as a *nice to have*, but maybe this addon would never exist had this been the situation before, so 👍 for removing it.

**Comment by pedrobaeza** [comment]
Closing then as decided.

**Pull request closed without merging**
