### PR TITLE
[13.0] [MIG] mail_full_expand: Module migrated in v13.

### PR DESCRIPTION
**Pull request by Chandresh-SerpentCS**

### CODE REVIEW

**Comment by Chandresh-SerpentCS** [comment]
Request for review. @bodedra @dreispt

**Comment by tonygalmiche** [comment]
you have to use "black, isort and prettier"
see https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0
thank you in advance

**Comment by bodedra** [comment]
@Chandresh-SerpentCS would you please attend comment from @tonygalmiche ?

**Comment by bodedra** [comment]
Ping @Chandresh-SerpentCS

**Comment by Chandresh-SerpentCS** [comment]
@bodedra @tonygalmiche I have created a new PR #636. I am going to close this PR.

**Pull request closed without merging**
