### PR TITLE
[15.0][UPD] Eficent -> ForgeFlow

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Leftovers.

### CODE REVIEW

**Review by BernatPForgeFlow — APPROVED** [review]

**Review by BernatPForgeFlow — APPROVED** [review]
LGTM!

**Review by flotho — COMMENTED** [review]
hi,
thanks for this proposal.
I'm wondering if the OCA recommandations weren't to add copiright in the readme or licence file inseated of each python file?

**Review by HaraldPanten — APPROVED** [review]
@rafaelbn could you merge?

**Review by rafaelbn — APPROVED** [review]

**Comment by rafaelbn** [comment]
Hello @flotho , in this moment I don't remember clearly I think usuale every one base on the module template: https://github.com/OCA/maintainer-tools/tree/master/template/module

You can read also https://github.com/OCA/maintainer-tools/issues/86

And finally https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst

If this don't clarify the we should improve the documentation 😄 (is a possibility)

**Pull request merged**
