### PR TITLE
[13.0][MIG] base_search_mail_content: Migration to 13.0

### PR DESCRIPTION
**Pull request by ernestotejeda**
supersedes https://github.com/OCA/social/pull/565

I squashed administrative commits too

cc @Tecnativa TT19710

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]
Tested on runbot and code LGTM! :+1:

**Review by pedrobaeza — APPROVED** [review]
Code and functional review

**Review by rafaelbn — APPROVED** [review]

**Pull request merged**
